### ISSUE TITLE
ux changes form

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#106]
add day name next to the date.

Instead of:

July 3 $50
Friday, July 3 $50

____

add a a line in total area for "VAT" (tax) 10%

**Comment by bamboochow** [comment]
@atharva3010  here ya go
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-%40PaulChrisLuke?node-id=0%3A1

**Comment by atharva3010** [comment]
okay
