### ISSUE TITLE
final revision hitlist

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#107]
1. I changed "sales" to "lease" in the database, their request. This probably requires a code change
2. I added a new category "ecotourism" and re-categorized some of that content. 
3. about us in footer should open in new tab

**Comment by paulchrisluke** [comment]
4. add "in the press" to footer, link to /listing/in-the-press

**Comment by paulchrisluke** [comment]
5. corp retreat url was updated, so the image on the home page should link to: 

/listing/Large-Company-Retreats-in-Nature-and-Team-Building

and change image to https://res.cloudinary.com/die9ji2vn/image/upload/dpr_auto/w_auto/q_auto:low/f_auto/v1562223032/group/group-retreat_s3ksth.jpg

(also center the text)

**Comment by paulchrisluke** [comment]
6. add "starting from" next to price on accomodations on home page

![image](https://user-images.githubusercontent.com/5694308/60652584-b87a6480-9e72-11e9-84e1-4b10786ec682.png)

**Comment by bamboochow** [comment]
@paulchrisluke starting from added
