### ISSUE TITLE
add pvk page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#122]
I'll add this to the database, afterwards we will need to place a link in the top nav to get there

https://docs.google.com/document/d/10I3C5I7tanJSthxr2ydl6_1xay8aTO8N60Coam3WtOU/edit#heading=h.5t97a29uw2z7

"we can add PVK stand-alone category in top navigation bar and add description of PVK along with the 5 pictures to stay within template format" - client

**Comment by atharva3010** [comment]
Okay

**Comment by paulchrisluke** [comment]
page created, ready to add to nav https://vkirirom.com/listing/Pine-View-Kitchen-PVK

**Comment by atharva3010** [comment]
added
