### ISSUE TITLE
add multi language support

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#127]
working with @StrangeWill strangewill on this one... changing the database to support and adding i18n support, related to https://github.com/whynotearth/meredith-core/issues/20

adding translation tables... each have one row per language:
https://cdn.discordapp.com/attachments/467562027301470218/598021296529342514/unknown.png

**Comment by atharva3010** [comment]
sure

**Comment by StrangeWill** [comment]
Sort of -- i18n support has nothing to do with the API/database, it's a standard for content that is hard-coded into the site (headers, sections, buttons, input labels, etc.). This will be totally different from how the API works.

- Implement i18n support like normal.
- When the database gets multilingual support, you can provide the `accept-language` header to the API for it to determine what language content to attempt to pull (we'll need a default if that fails).

**Comment by paulchrisluke** [comment]
completed, moving more support to our other meredith-core pages here https://github.com/whynotearth/meredith-core/issues/154
