### ISSUE TITLE
ux - design sign up and booking flow

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#129]
this already basically exists here:
https://www.figma.com/file/T5TAyudgkq6xNHGIYKt8yb/Activity-bookingupdate-Copy?node-id=0%3A1

![image](https://user-images.githubusercontent.com/5694308/61051906-6ad29e80-a414-11e9-93d5-854c2640a9fb.png)

need to dark mode it and import into our new file here:
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by atharva3010** [comment]
afaik this has been completed is there anything else we need wrt design?

**Comment by paulchrisluke** [comment]
@Cheanataly are you making any other changes to the ux flow of this page?

**Comment by Cheanataly** [comment]
Nope, it is like the previous flow.
