### ISSUE TITLE
gallery feature

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#13]
- on mobile home page we have a gallery option for people to swipe through:
![image](https://user-images.githubusercontent.com/5694308/59322552-d257da00-8d00-11e9-83fd-70a4d3eef563.png)

- on listing page, include gallery when clicking on image area, allow lots of pictures.

- copy airbnb:
https://www.airbnb.com/rooms/943864?source_impression_id=p3_1560311859_5Le9N2yNnP8wRm%2FW

![Uploading image.png…]()

**Comment by paulchrisluke** [comment]
Still working on the dots getting to the style we want. Gallery also causes increased load time. May need to think about rebuilding this as a custom component rather than use the existing. Possibly a good student job.

**Comment by paulchrisluke** [comment]
lets take another pass at this, I don't like how our lighthouse scores are low from this

**Comment by atharva3010** [comment]
Okay
