### ISSUE TITLE
sitemap 404 issue

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#130]
our sitemap needs help. We should help it... 

![image](https://user-images.githubusercontent.com/5694308/61054043-edf5f380-a418-11e9-9fe3-9a4bd86f4f38.png)

For some reason using vue's version of routes is not working. Will suggested maybe rolling its own node server to deliver the sitemap file?

**Comment by atharva3010** [comment]
Okay

**Comment by mort3za** [comment]
@atharva3010 @paulchrisluke Just noticed that sitemap generation is inside client app. It's wrong, we should have an expressjs app to handle it.
Where can I run a simple expressjs server?

**Comment by paulchrisluke** [comment]
going to use netlify functions to run the express.js:

https://www.netlify.com/blog/2018/09/13/how-to-run-express.js-apps-with-netlify-functions/

```
You do have the ability to cache stuff in a /temp directory too.
so you don't have to be banging against the API and crawling all pages every request.
though for your first pass -- that's fine.
```

**Comment by paulchrisluke** [comment]
done
