### ISSUE TITLE
ux - design booking flow (dark mode)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#134]
take from here and add to airbnb dark mode figma file:

https://www.figma.com/file/T5TAyudgkq6xNHGIYKt8yb/Activity-bookingupdate-Copy?node-id=0%3A1

![image](https://user-images.githubusercontent.com/5694308/61169590-a04cc880-a589-11e9-97d8-903d4ef112e5.png)

**Comment by Cheanataly** [comment]
All the version or only desktop version, sir?

**Comment by paulchrisluke** [comment]
@Cheanataly sorry for missing this, mobile as well please... preferably, always design mobile first

**Comment by Cheanataly** [comment]
Well, sir. I would design the desktop first and make the flow of website for Mr. Atharva Sharma.
