### ISSUE TITLE
ux design profile page (dark mode)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#135]
take from here and add to airbnb dark mode:

https://www.figma.com/file/T5TAyudgkq6xNHGIYKt8yb/Activity-bookingupdate-Copy?node-id=0%3A1

![image](https://user-images.githubusercontent.com/5694308/61169600-bb1f3d00-a589-11e9-8445-5c30984d369c.png)

**Comment by paulchrisluke** [comment]
@Cheanataly this is done correct?

**Comment by Cheanataly** [comment]
@paulchrisluke Yeah, it is done.
