### ISSUE TITLE
[content] create bus shuttle information page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#163]
Mr. Hicki is looking for a shuttle bus information page

https://docs.google.com/document/d/10I3C5I7tanJSthxr2ydl6_1xay8aTO8N60Coam3WtOU/edit#heading=h.ejmka7adpek6

**Comment by dalya122899** [comment]
Sir, here is the information about shuttle bus. 
I list down all the information on the very bottom part of document in the link below 
https://docs.google.com/document/d/10I3C5I7tanJSthxr2ydl6_1xay8aTO8N60Coam3WtOU/edit#

**Comment by paulchrisluke** [comment]
great, work with @SoksanSerey and get it the content added to our database files here:

https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=0

and here:

https://docs.google.com/spreadsheets/d/1nK15V2k0vu6Nyvt7pxbKeL5hlyItwaHsIScQzmeRmFI/edit#gid=0

**Comment by paulchrisluke** [comment]
@DaroDalya was this ever added to the spreadsheet

**Comment by DaroDalya** [comment]
@paulchrisluke not yet sir. I will add it now.

**Comment by paulchrisluke** [comment]
this page has been added and ready for review https://vkirirom.com/listing/Shuttle-Bus
