### ISSUE TITLE
[content] Create large group marketing pages

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#165]
Do some keyword research and decide on 4 title's with keywords to target large group customers. 

https://medium.com/marketing-by-kevin/beginner-seo-guide-how-to-do-keyword-research-893492e75dc4
https://medium.com/@RiojaAlejandro/how-to-do-keyword-research-and-use-keywords-in-your-posts-the-complete-guide-2018-79760e83876b

Hicki can tell you a little bit about the customer and what they are looking for. The goal is to post these pages on facebook and attract a large group customer to fill out the form. Each one of these conversions is worth a lot of money, so its big KIT points.

Then write content for the 4 new pages and add them to our google sheet database @SoksanSerey can tell you more about that. 

Once they are added we should have a figma file ready for preview to show Mr. Hicki. Once he approves, provide that to the facebook team to post and then we track conversions.

**Comment by hickio** [comment]
I think this one is worth brainstorming on or at least doing face to face to discuss.  We could add on agenda as part of Thursday meeting and I can invite my sales manager to join.
Off the top of my head, we have below types of large group customers (may have more):
1) NGOs
2) School study tours
3) Ministries from various governments
4) Large companies

**Comment by hickio** [comment]
Nuance and priorities may slightly differ between these groups, but they select us for below reasons as outlined in our website

Top Ten Reasons to Select vKirirom for your next Corporate Retreat

Large groups welcome!
Cool off surrounded by nature
Professional meeting environments
Strengthen your team with array of vKirirom Team building activities
Party into the night!
Good food
Just 3 hours from Phnom Penh and half the distance to Sihanoukville
Reward staff and create memorable experience
Explore rare Cambodia pine forest
Passionate staff to serve you

**Comment by hickio** [comment]
I will talk to Ms. Nimol, my group customer sales manager, to brief her on what we are trying to achieve and you guys can interview her on Tuesday or Wednesday and show us your idea during Thursday meeting

**Comment by hickio** [comment]
I talked to Ms. Nimol this morning and she is happy to provide input.  I have sent google hangout meeting request for the three of you at 4:30pm today.  Note I will not participate.

**Comment by dalya122899** [comment]
@hickio Yes, noted sir!

**Comment by hickio** [comment]
After the meeting, you need to be clear on the following:
1) Types of group customer segments
2) Requirements that are most important to each of these customer segments related to their decision making when choosing where to hold their company retreat

**Comment by dalya122899** [comment]
@paulchrisluke @hickio 
Here is the link for large group pages content that I have prepared
1. School trip https://docs.google.com/document/d/15wmILChD8Y7ewCb1PP35tQYFrpoF5DBRX9LZE340zxk/edit?usp=sharing
2. Travel agency 
https://docs.google.com/document/d/1ypkBB5rZ34CRX3zqxw7TyzS1U8VXNjFcQNijsN34d7g/edit?usp=sharing
Please check it.

**Comment by paulchrisluke** [comment]
"sorry for missing your message. I like it, but we should take contact info off the bottom and try and get people to submit the form so we can track how many people you converted
in your copy, you can say something like discounts available, fill out the form for exclusive pricing or something like that"

also @atharva3010  how do we setup a new form notification? I was going to use "services" category in the db, and change it to "sales"

**Comment by sotheaYouk** [comment]
Corporate retreat: https://docs.google.com/document/d/1EBgieNujvbBIsmXDAD0YIMlyVuUFQ9NJjjuG_-Sippo/edit

NGOs: https://docs.google.com/document/d/157IUe6A_HeNCik7_hshnQzK4dSga3rLyLW80XJaR8UU/edit

@hickio  @paulchrisluke  Corporate and NGOs pages are finished, please check.

**Comment by paulchrisluke** [comment]
I have reviewed and approve. Please get approval from @hickio and provide a posting schedule with your target keywords

**Comment by DaroDalya** [comment]
@paulchrisluke Here is the posting schedule for the Large group marketing page 
1. Group retreat: Saturday (07, Sep 2019) at 6 am
2. Travel agency: Wednesday (11, Sep 2019) at 1 am 
3. School trip: Sunday (15, Sep 2019) at 5 am 
4. NGOs: Wednesday ( 18, Sep 2019) at 1 am

**Comment by paulchrisluke** [comment]
@DaroDalya this looks great, have you cordinated with Mr. Sochet so that he can post the pages on social media as well? I will post these pages in the morning on each day. Can you send me a calendar invite for each day to remind me?

**Comment by hickio** [comment]
So so so sorry for being delinquent.  So many fires the last couple of weeks to deal with.

Content looks great.  Let's keep driving and experimenting.  Please post
