### ISSUE TITLE
[soksan_serey] json generation for seo

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#170]
https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=550121964

In column K, we have a field which accepts json. We use this to add structured data to the head of each page. 

Here is an article about structured data and why it's important (its basically tagging your page to be seo ready): https://neilpatel.com/blog/structured-data/

Right now, we use the same schema for every page, which is not the best.  our blog articles should have the article schema, the events should have events, etc. 

First, identify the schema markup you think would be best for each page category. Then generate the schema for each category/page and submit here for review. 

- json generated and validated via https://technicalseo.com/tools/schema-markup-generator/ https://search.google.com/structured-data/testing-tool/u/0/

also on json remember to add keywords because the generator doesn't do that for you. Example
```
{"url": "https://www.vkirirom.com", "name": "vKirirom Pine Resort", "@type": "Hotel", "email": "info@vkirirom.com", "image": "https://res.cloudinary.com/die9ji2vn/image/upload/dpr_auto/w_auto/q_auto:low/f_auto/v1560155423/top_image_kyv74r.jpg", "keywords":"Content SEO, Google Analytics, Mobile SEO, Security, Site Speed, Site Structure, Technical SEO, WordPress, Yoast SEO"},"hasMap": "https://goo.gl/maps/k9FTeb4krNLsyfKp8", "sameAs": ["https://www.instagram.com/vkirirom_pine_resort/", "https://www.facebook.com/vkirirom/", "https://www.tripadvisor.com/Hotel_Review-g8747107-d7271576-Reviews-VKirirom_Pine_Resort-Traeng_Trayueng_Kampong_Speu_Province.html"]
```

@sotheaYouk and @dalya122899 can help doing keyword research for each page. I'll make a new issue for that

**Comment by DaroDalya** [comment]
@paulchrisluke We have finish json generation for all page. please check it.
https://docs.google.com/spreadsheets/d/1zD7upngQv1fWTukZKmg4-H0YprWMPan7XK81VZTAW58/edit#gid=0

**Comment by paulchrisluke** [comment]
this looks great. Please add to the main sheet https://docs.google.com/spreadsheets/u/2/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=550121964

and I'll add to the site. Once I add to the site, we can verify on the live site.
