### ISSUE TITLE
[seo] keyword research for all current pages

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#171]
I have added a new column in the pages sheet for keywords. Research keywords we should use for each page, and enter them in that column (`, `) in between each. Like this:

`Content SEO, Google Analytics, Mobile SEO, Security, Site Speed, Site Structure, Technical SEO, WordPress, Yoast SEO`

**Comment by sotheaYouk** [comment]
@paulchrisluke 
Keyword research is done and ready for review.
https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=550121964

**Comment by paulchrisluke** [comment]
this is very good, @SoksanSerey you can update your json with these keywords now

**Comment by SoksanSerey** [comment]
@paulchrisluke got it 😊
