### ISSUE TITLE
Get new photos 

### ISSUE THREAD

**Issue by sotheaYouk** [whynotearth/hotel-website-vkirirom.com#174]

**Comment by sotheaYouk** [comment]
New accommodation photos edited

**Comment by sotheaYouk** [comment]
@paulchrisluke new accommodation photos updated in the "public" doc
link: https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=550121964 (see the rows in "Pages" and "Images" that are highlighted in green)

**Comment by paulchrisluke** [comment]
updated, please review, if good. close
