### ISSUE TITLE
[seo] keyword research for all the pages of KIT website content 

### ISSUE THREAD

**Issue by DaroDalya** [whynotearth/hotel-website-vkirirom.com#175]
research for 5 SEO keywords for each page of the KIT website

**Comment by DaroDalya** [comment]
@paulchrisluke we have done the SEO keyword research for the KIT website and here is the link
https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit?ts=5d52a1bc#gid=550121964
column N in that google sheet

**Comment by paulchrisluke** [comment]
looks great! I'll load this in when we start making moves to KIT's site
