### ISSUE TITLE
PWA blog

### ISSUE THREAD

**Issue by sotheaYouk** [whynotearth/hotel-website-vkirirom.com#177]
The pwa blog is finished and ready for review, check here: https://docs.google.com/document/d/10De0lLd8xcIusvz5b0L98dHJxsFR8KOZzwZRvCatseE/edit

It's been uploaded to the google sheet too, check here: https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=550121964

Posting schedule: October 10, 2019. 

@paulchrisluke

**Comment by hickio** [comment]
I don't understand purpose of this post.  It is well written but why are we encouraging use of PWA?  What is benefit to us in doing so?

**Comment by paulchrisluke** [comment]
@hicki , the purpose of the blog is to help with student recruitment. Showing that we are building real tools that are live in the world is a good way to show incoming students that we are actually making cool stuff! 

@sotheaYouk I think the blog is great, maybe add some screenshots of our analytics to show the proof of the numbers we are showing. You can get those screenshots from Makoto

**Comment by hickio** [comment]
@chris thanks for the explanation.  If so, let's also get a cool picture of our team working on it in a way that visualizes this point.  It will have to be produced and needs to be symbolic.

**Comment by sotheaYouk** [comment]
@paulchrisluke I added a screenshot of our analytics and an image of our team working already. Please check
