### ISSUE TITLE
login/sign up buttons with social do not function

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#178]
https://staging.vkirirom.com/listing/Bell-Tent

Desktop, chrome.
Fill out form, click login
see the popup
click buttons, no response.

![image](https://user-images.githubusercontent.com/5694308/66975188-ebfe9900-f0c7-11e9-8156-f241ce7d2820.png)

**Comment by atharva3010** [comment]
fixed, closing
