### ISSUE TITLE
Create new Search Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#192]
this looks good so far, can you please provide the mobile version as well?

**Comment by Cheanataly** [comment]
Okay.

**Comment by Cheanataly** [comment]
I have done the mobile version and it is ready for you to check up.

**Comment by paulchrisluke** [comment]
Comments in dogma added

**Comment by Cheanataly** [comment]
I have changed and anything more needs to modify?

**Comment by paulchrisluke** [comment]
be sure to move your cards into "ready for review" when you are ready for that. But no, looks good, all done!
