### ISSUE TITLE
explore existing lottie library to see where we can add a bit of flair to our site.

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#197]
check out lottie animations here, and see what icon packs or animations may work to make our site prettier, let me know which ones you think would work well and where. Its ok of they are premium packs or paid animations, we can pay for them.

https://lottiefiles.com/marketplace/ecommerce-animations

**Comment by Cheanataly** [comment]
Can I come up the animation with my own idea?

**Comment by paulchrisluke** [comment]
Yes

**Comment by Cheanataly** [comment]
If I come up with my idea, then I have to make after effect to show you? Right?

**Comment by paulchrisluke** [comment]
Yep!
