### ISSUE TITLE
check checkout prorcess ux

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#201]
shinta mani wilds checkout process was veryr thoughtful. Go to staging.vkirirom.com and checkout on desktop on mobile. Tell me if its good ux. Try and birng in line with shinta mani wilds flow and ux. leave comments on figma for natalay to do

**Comment by paulchrisluke** [comment]
@Cheanataly when you finish the mobile versions of these, please let us know in this issue.

**Comment by Cheanataly** [comment]
Yeah, I have done it.
