### ISSUE TITLE
resolve credit card error on netlify

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#203]
we have an invalid credit card listed on netlify, and our site will be shut down in 20 days. Please switch the credit card to a valid credit card. Log in to netlify.com and update the billing info

![image](https://user-images.githubusercontent.com/5694308/68747217-abddf800-062c-11ea-992f-8134d5a37927.png)

**Comment by chheanpisethpanha** [comment]
Who should I contact regarding the credit card?

**Comment by paulchrisluke** [comment]
zeal@kit.edu.kh
or Mr. Leo

**Comment by chheanpisethpanha** [comment]
@paulchrisluke Sir, the issue is resolved!
