### ISSUE TITLE
Update Listing Page Design

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#211]
### Previous Design
Our current accomodation design includes descriptions with a booking form to fill out on the page.
![image](https://user-images.githubusercontent.com/5694308/68850907-765a0d00-0707-11ea-9cca-8e2173d6957e.png)

### Desktop
Accomodation page designs updated to only show accomodation descriptions 
![image](https://user-images.githubusercontent.com/34535916/70974569-a451b900-20da-11ea-9f4e-35f9addadb26.png)

basically, remove booking form, expand text spacing, decrease left/right margins 
The title apart from the accommodation name is H2

Leading to book now button #212  
![image](https://user-images.githubusercontent.com/5694308/68850554-d00e0780-0706-11ea-9029-7bb98584f5ee.png)

### Mobile
Mobile version: The title apart from accommodation name is H3
![image](https://user-images.githubusercontent.com/34535916/70975032-b54efa00-20db-11ea-946b-a636e55ad452.png)

### Extra Info

Related pull requests: 
https://github.com/whynotearth/hotel-website-vkirirom.com/pull/10
https://github.com/whynotearth/hotel-website-vkirirom.com/pull/9

Design file here: https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by mort3za** [comment]
@paulchrisluke  The "getting around" section should be apart to separate sections similar to amenities, spaces, rules, ... so I can freely style them and move sections based on design.

**Comment by bamboochow** [comment]
@mort3za I moved the "cancellation policy" in the api to rules to separate from shuttle info, but markdown styling is not supported in that section, can you make sure that markdown is supported for the rules section?

**Comment by mort3za** [comment]
@bamboochow Sure, I'll add support markdown to all the text sections in the listing page and review rules.

**Comment by mort3za** [comment]
> I moved the "cancellation policy" in the api to "rules" to separate from "shuttle info" in the database
@bamboochow I changed the method of styling contents in listing page (and other pages that have markdown content).  
Now every `h2 title's` font-size is 34px in desktop and 20px in mobile.  
So we need to change titles to h2 in API markdown contents to have a consistent style.

**Comment by paulchrisluke** [comment]
this work is complete, assigned another issue for markdown updating https://github.com/whynotearth/hotel-website-vkirirom.com/issues/298
