### ISSUE TITLE
Booking Flow 1/9 - Book now Bottom Bar

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#212]
### Previous Design
The design right now includes a booking form that we are replacing
![image](https://user-images.githubusercontent.com/5694308/68851140-e23c7580-0707-11ea-94e3-f49bdced84f8.png)

### Desktop
Add book now bottom bar to accomodation pages identical in function to [shinta mani wild's book now bar](https://github.com/whynotearth/shinta-mani-wild/issues/27): booking bar will stick to bottom of window until visitor scrolls to bottom of page where it will stick directly on top of footer

![image](https://user-images.githubusercontent.com/5694308/68850554-d00e0780-0706-11ea-9029-7bb98584f5ee.png)

Position shown here : 
![image](https://user-images.githubusercontent.com/5694308/68853558-d69f7d80-070c-11ea-81d7-b78c408ba9fd.png)

Bar background color: #191C21 
Button color: #F7B947
Shadow: 
`
box-shadow: 0px 9px 24px rgba(0, 0, 0, 0.25), 0px 4px 4px rgba(0, 0, 0, 0.25);
`

![image](https://user-images.githubusercontent.com/5694308/68851435-89b9a800-0708-11ea-856d-643a5a498f8e.png)

### Mobile
Mobile follows same color scheme, with different sized fonts 
![image](https://user-images.githubusercontent.com/5694308/68854079-e10e4700-070d-11ea-8de3-c5f1e6eaac76.png)
![image](https://user-images.githubusercontent.com/5694308/68853811-647b6880-070d-11ea-97ea-9608432f7aa6.png)
With this exact alignment, text to button

### Extra Info
All related pull- requests: 
https://github.com/whynotearth/shinta-mani-wild/pull/58
https://github.com/whynotearth/shinta-mani-wild/pull/64
https://github.com/whynotearth/shinta-mani-wild/pull/288
https://github.com/whynotearth/shinta-mani-wild/pull/134

Design file here: https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by paulchrisluke** [comment]
@mort3za 
Just tested the deploy preview, the booking bar needs to do sticky scroll where it sticks to the bottom of the window just like shinta mani 
https://shintamaniwild.com/listing/wild-tents

**Comment by mort3za** [comment]
@paulchrisluke Seems it's a bug, in second refresh works. will fix it, thanks.

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/71335634-3abc2980-2576-11ea-8543-ee0055c24b5a.png)
Booking bar has incorrect font, see if related to this issue #252 
@mort3za
