### ISSUE TITLE
Booking Flow 2/9 - Confirm Dates

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#214]
### Previous Design 
![image](https://user-images.githubusercontent.com/5694308/68855620-3435c900-0711-11ea-8d72-7918adefb8d2.png)

### Desktop

**Check in/out, month color**: #4B7F52
**Booked Calendar Dates**: #4f4f4f
**other chosen dates (lighter green)**: #77C381
**Active button**: background: #F7B947  Text: 191C21
**Inactive button**: background: #B9BCC1 text: E1E7ED

![image](https://user-images.githubusercontent.com/5694308/69472952-1d633680-0de3-11ea-90b6-09e36648ddbb.png)
Inactive calendar dates will be in gray and cannot be clicked 

![image](https://user-images.githubusercontent.com/5694308/68858227-25521500-0717-11ea-86d5-5860d0cbbbac.png)
Expected action when pressing button on booking bar #212 
![image](https://user-images.githubusercontent.com/5694308/68859031-f50b7600-0718-11ea-8bc8-bad61e8ef968.png)

We expect the screen to blur out the rest of the page as a iphone sized pop-up show up in the center.
`
background: rgba(0, 0, 0, 0.4);
`
`
filter: blur(8px);
`

They can pick a check in date 
![image](https://user-images.githubusercontent.com/5694308/68859500-f5f0d780-0719-11ea-8d8e-9169cd2a5695.png)

Once they pick a check out date, the bottom will show dates and prices, as well as total 
![image](https://user-images.githubusercontent.com/5694308/68859348-a8746a80-0719-11ea-9b9b-4cea6d27e812.png)

The price of each date is dependent on day of week selected, base on api 
Clicking 'X' will exit and return to the accomodation page with no blur.

### Mobile 

**Check in/out, month color**: #4B7F52
**other chosen dates (lighter green)**: #77C381
**Active button**: background: #F7B947  Text: 191C21
**Inactive button**: background: #B9BCC1 text: E1E7ED

![image](https://user-images.githubusercontent.com/5694308/68858302-53375980-0717-11ea-8fd5-59614a2b88e6.png)

Expected action when pressing button on booking bar #212 
on mobile, we expect the whole calendar picking image to populate the mobile screen, so no blurred out accomodation page. 
![image](https://user-images.githubusercontent.com/5694308/68858360-795cf980-0717-11ea-8dc0-e3715a1c760a.png)
![image](https://user-images.githubusercontent.com/5694308/68858972-da390180-0718-11ea-8162-63567a99b023.png)

They can pick a check in date 
![image](https://user-images.githubusercontent.com/5694308/68859500-f5f0d780-0719-11ea-8d8e-9169cd2a5695.png)

Once they pick a check out date, the bottom will show dates and prices, as well as total 
![image](https://user-images.githubusercontent.com/5694308/68859348-a8746a80-0719-11ea-9b9b-4cea6d27e812.png)

The price of each date is dependent on day of week selected, base on api
Clicking 'X' will return to accomodation page

### Extra Info

Design File: https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8237%3A0

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/71335723-b1f1bd80-2576-11ea-88a7-913940d8c3f6.png)
no rounded corners on the chosen ones 

![image](https://user-images.githubusercontent.com/5694308/71335772-e9f90080-2576-11ea-82b5-d75b18836ce6.png)
No hover or click interaction 

![image](https://user-images.githubusercontent.com/5694308/71335816-1745ae80-2577-11ea-99ce-356ed891d0c1.png)
Make margins match designs as well as align x

**Comment by mort3za** [comment]
@paulchrisluke I fixed the margins of dialog and spacings but the datepicker's width is hardcoded in plugin to 300px, can't resize to match the alignment of header and other parts.

**Comment by paulchrisluke** [comment]
ok @mort3za don't worry about it for now
