### ISSUE TITLE
Booking Flow 4/9 - Confirm Guests

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#219]
This is part 4 of 9 of the booking flow, when closed please refer to #213 and check off.

### Previous Design 
Current designs do not have a "number of guests" question 
![image](https://user-images.githubusercontent.com/5694308/68916757-f466f400-0799-11ea-9cde-9fdc4727b016.png)

### Desktop
![image](https://user-images.githubusercontent.com/5694308/70876246-6c1f7d00-1feb-11ea-8c2e-6aac21337d73.png)

Expected behavior is once user clicks "Log In" or logs in with FB/Google in previous step #218 the pop-up changes to the confirm guest screen here

![image](https://user-images.githubusercontent.com/5694308/70876273-8fe2c300-1feb-11ea-9fb8-048d4d78da3f.png)

The bed type options available for each accomodation type is displayed here as buttons. Inactive states are darker when not chosen. If there's only one option, then default display the one active option as a large button.

![image](https://user-images.githubusercontent.com/5694308/70875932-4d6cb680-1fea-11ea-945f-2d827dfc3aae.png)

![image](https://user-images.githubusercontent.com/5694308/68917516-2e85c500-079d-11ea-832b-16456852a803.png)
Users click + or - to choose how many guests they have 

![image](https://user-images.githubusercontent.com/5694308/68917528-43faef00-079d-11ea-8ba9-1b573e321d61.png)
Total guests will show below 

If total guests is 0, then make button inactive 
![image](https://user-images.githubusercontent.com/5694308/68917568-77d61480-079d-11ea-8143-58467562f6bd.png)

Active button: background: #F7B947 Text: 191C21
Inactive button: background: #B9BCC1 text: E1E7ED

### Mobile
![image](https://user-images.githubusercontent.com/5694308/70876309-b43e9f80-1feb-11ea-8dab-6f65c3cc6d0a.png)

Expected behavior is once user presses "Log In" or logs in with FB/Google in previous step #218 screen changes to confirm guest screen here

![image](https://user-images.githubusercontent.com/5694308/68917516-2e85c500-079d-11ea-832b-16456852a803.png)
Users click + or - to choose how many guests they have 

![image](https://user-images.githubusercontent.com/5694308/68917528-43faef00-079d-11ea-8ba9-1b573e321d61.png)
Total guests will show below 

If total guests is 0, then make button inactive 
![image](https://user-images.githubusercontent.com/5694308/68917568-77d61480-079d-11ea-8143-58467562f6bd.png)

Active button: background: #F7B947 Text: 191C21
Inactive button: background: #B9BCC1 text: E1E7ED

### Extra Info

Design File: https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8237%3A0

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/71053002-b0dc1d00-217f-11ea-8351-efb1b4b0b65b.png)

We want only gray and light gray for active/inactive states, so change the color from the green to gray for active/inactive buttons 

We're getting new icons too, so you can do that when we get our new icons

**Comment by mort3za** [comment]
@paulchrisluke PR updated.

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/71336206-ca62d780-2578-11ea-9829-f17668053c39.png)
Top margin and x alignment needs to be the same as design 
![image](https://user-images.githubusercontent.com/5694308/71336374-6f7db000-2579-11ea-8849-c47f34dd1146.png)

![image](https://user-images.githubusercontent.com/5694308/71336325-347b7c80-2579-11ea-874e-0f8b1a324e39.png)
Remove infant option in guest choice 
![image](https://user-images.githubusercontent.com/5694308/71336348-5117b480-2579-11ea-8151-3db7bc93dee5.png)
Change to Children under 5 only 

![image](https://user-images.githubusercontent.com/5694308/71336393-8a502480-2579-11ea-9c74-d76f9925b856.png)
Add max info as text on guest selection 

![image](https://user-images.githubusercontent.com/5694308/71336600-6b9e5d80-257a-11ea-9811-5b25f434c97f.png)
remove this error, and instead prevent the + from being clickable when at max capacity. 
![image](https://user-images.githubusercontent.com/5694308/71336671-bae48e00-257a-11ea-9957-e2b5844bc4bf.png)

![image](https://user-images.githubusercontent.com/5694308/71336687-cfc12180-257a-11ea-8980-64a21a55415f.png)
Right now the option does not autoselect. For accomodations where there's only one option, auto select the only option available

**Comment by mort3za** [comment]
@paulchrisluke By removing the error message we should disable (+) buttons until user selects a bed type or hide the entire row of adults and children count selection. Because we don't know amount of capacity. Which way is better you think? (currently I disabled + buttons)

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/71387624-461b5d80-2627-11ea-9564-67f8d06728a7.png)
we do know the amount of capacity, its listed in the database 

![image](https://user-images.githubusercontent.com/5694308/71387682-85e24500-2627-11ea-89a5-4f50464d2fa0.png)
We need to display this capacity number in the "max ____ people message". Remove the infant policy, that's for airbnb, not for us. 

disable + button right now is fine, we'll keep that

**Comment by mort3za** [comment]
In Figma I see two designs, one with header image, another without header image. Should I implement that header image?  
And that huge space above submit button is correct? or you mean the modal should be full height in mobile and the button should stick to bottom?

**Comment by mort3za** [comment]
In Figma I see two designs, one with header image, another without header image. Should I implement that header image?  
And that huge space above submit button is correct? or you mean the modal should be full height in mobile and the button should stick to bottom?
@paulchrisluke

**Comment by paulchrisluke** [comment]
add header image. We are trying to make each booking card consistant UX... title image first, then info, buttons at the bottom etc. Yes the huge space above submit is correct. 

as far as sizing, just trying to make sur ethe cards don't resize each step, should feel like the same card is simply getting refreshed with new info each time.

**Comment by bamboochow** [comment]
> And that huge space above submit button is correct? or you mean the modal should be full height in mobile and the button should stick to bottom?

Yes, he just saw this, he said yes
