### ISSUE TITLE
Booking Flow 7/9 - Customer Info

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#222]
### Previous Design
![image](https://user-images.githubusercontent.com/5694308/68986575-3b64f000-0853-11ea-98a0-253e6fc305a5.png)

Current designs do not have specifics about customer groups 

### Desktop

![image](https://user-images.githubusercontent.com/5694308/70877632-dc7ccd00-1ff0-11ea-9699-3ae0e5dea791.png)

New design has info component similar to #220 

They can exit booking process early by clicking vkririom logo to return to home. 

When we're on this page, the booking nav should show that this is on the Customer Info Page #248 

![image](https://user-images.githubusercontent.com/5694308/68986673-42d8c900-0854-11ea-9700-3c15464a8ffa.png)

### Mobile 
![image](https://user-images.githubusercontent.com/5694308/70877679-151ca680-1ff1-11ea-9101-527b85221c7b.png)

Clicking "x" closes booking process, returns to accomodation
![image](https://user-images.githubusercontent.com/5694308/68986811-e5457c00-0855-11ea-809a-0fe7a0ec2cf9.png)

No changes in font sizing/case

### Extra Info

Design File: https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8237%3A0

**Comment by mort3za** [comment]
We should change that phone field's design because we're using Vuetify. Please check the examples in this page: https://vuetifyjs.com/en/components/text-fields  

Should I add any mask for the phone number? (I mean forcing the format of input to something strict).

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/71336837-760d2700-257b-11ea-912f-c45a2d53b5f3.png)
Missing divider lines as shown in design below 
![image](https://user-images.githubusercontent.com/5694308/71336857-89b88d80-257b-11ea-96b8-da70bf2e01d2.png)

![image](https://user-images.githubusercontent.com/5694308/71336980-1fecb380-257c-11ea-91b3-13ab96d4a42d.png)
Hide the x in this section so they cannot exit out of the booking process prematurely (showing screenshot for review rules, but same concept)

**Comment by mort3za** [comment]
@paulchrisluke I see nothing new, moved to Review in progress.
