### ISSUE TITLE
Booking Flow 8/9 - Payment Info

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#223]
### Previous Design
![image](https://user-images.githubusercontent.com/5694308/68986871-7e749280-0856-11ea-8f3b-b331fc873312.png)

This payment info process is not specific enough, does not show any booking details at all 

### Desktop
![image](https://user-images.githubusercontent.com/34535916/70973503-5b006a00-20d8-11ea-8b6f-e103fc6a93d4.png)

Adds a info section that shows booking info while going through flow. 

They can exit booking process early by clicking vkririom logo to return to home. 

It doesn't have any Footer for both Desktop and Mobile version.

When we're on this page, the booking nav should show that this is on the Payment Info Page (WILL LINK ISSUE @bamboochow )

![image](https://user-images.githubusercontent.com/5694308/68986909-c693b500-0856-11ea-8c5d-cf9fc7a7d5c3.png)

The card info fill in field will not be visible UNLESS visitor chooses "pay with card" option, at which point it will slide out and visible. 

![image](https://user-images.githubusercontent.com/5694308/70491620-5534e280-1b34-11ea-904b-852727ce293f.png)
![image](https://user-images.githubusercontent.com/5694308/70491634-5ebe4a80-1b34-11ea-9fec-55bd2e79442e.png)
Something like this 

### Mobile 
![image](https://user-images.githubusercontent.com/5694308/68986995-7f59f400-0857-11ea-90df-c5f2bb240efd.png)

Clicking "x" closes booking process, returns to accomodation
![image](https://user-images.githubusercontent.com/5694308/68986811-e5457c00-0855-11ea-809a-0fe7a0ec2cf9.png)

No changes in font sizing/case

### Extra Info

Design File: https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8237%3A0

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/71336837-760d2700-257b-11ea-912f-c45a2d53b5f3.png)
Missing divider lines as shown in design below 
![image](https://user-images.githubusercontent.com/5694308/71336857-89b88d80-257b-11ea-96b8-da70bf2e01d2.png)

![image](https://user-images.githubusercontent.com/5694308/71336980-1fecb380-257c-11ea-91b3-13ab96d4a42d.png)
Hide the x in this section so they cannot exit out of the booking process prematurely (showing screenshot for review rules, but same concept)

**Comment by bamboochow** [comment]
Will close issue and write any more edits as separate issue, we're in polishing stage and this major feature is done
