### ISSUE TITLE
Credit Card Number Input Field Issue

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#225]
This bug exists within the booking flow of vkirirom
vkiriom.com/reservation/confirmandpay

![image](https://user-images.githubusercontent.com/5694308/68930306-a4e7ee80-07c0-11ea-9ab5-7f841cf87892.png)

Instead of rejecting new numbers in a full input fields, it will push the rest of the numbers and drop the last number 

Here, I'm inserting number 9 into a series of 1234's 
![image](https://user-images.githubusercontent.com/5694308/68930405-e2e51280-07c0-11ea-98bf-0c57d0124f52.png)
![image](https://user-images.githubusercontent.com/5694308/68930442-fbedc380-07c0-11ea-8504-3f46b13bdad7.png)

Once I delete the 9, the 4 at the end does not come back
![image](https://user-images.githubusercontent.com/5694308/68930487-132cb100-07c1-11ea-8af9-b38acdf89c43.png)

This is the same for dates and ccv

**Comment by mort3za** [comment]
We don't manage these kinds of things in card number and CVV fields, Stripe creates these fields outside our app and inject them to our page.  
Also, I don't think that's a big issue. Anyway we can submit an issue in [Stripe project](https://github.com/stripe/react-stripe-elements) if you want.

**Comment by paulchrisluke** [comment]
ah don't worry about it for now, closing
