### ISSUE TITLE
New Top Navigation

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#227]
This is the new design for the site's desktop top navigation

![image](https://user-images.githubusercontent.com/5694308/69326381-47e7af00-0c7e-11ea-987b-17773c09de52.png)

Navigation will be 5 separate items, two with drop downs, in the bullet points below. The separate items are: 
- Accomodation
- Activities  
  - Events
  - Experiences
- Food 
  - Restaurant
  - Menu
- Blog
- Log in/Profile
  - Upcoming Trips
  - My Profile
  - Log Out

![image](https://user-images.githubusercontent.com/5694308/69522470-0e6fb600-0f94-11ea-855e-65129089b9f1.png)

Log in will switch to profile once site visitor has logged into their account, and "Profile" will show dropdown  

![image](https://user-images.githubusercontent.com/5694308/69327253-c98c0c80-0c7f-11ea-936a-4275ddd10dcd.png)

Design File: https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/70372240-08bc8d80-190f-11ea-87de-84bcb0aa20f5.png)

Make sure that the drop down colors matches the rest of the top nav design
background: 191C21
Text: B9BCC1

**Comment by sansNoms** [comment]
![image](https://user-images.githubusercontent.com/49821682/70372480-5c3dc580-1894-11ea-866b-3d822921fdad.png)

it's showing as this on my end.. also did not add the login as someone else is doing the log in. was the auth all done? I could wire it up if so.

**Comment by paulchrisluke** [comment]
this issue will be put on hold until log in process is done, it will stay in "in progress"

**Comment by paulchrisluke** [comment]
This also need the "upcoming trips" and "My Profile" pages. It is fine to use non-hyperlinked placeholders for now, we just want it there
![image](https://user-images.githubusercontent.com/5694308/70874203-aedd5700-1fe3-11ea-9477-5bdc211bca45.png)

**Comment by sansNoms** [comment]
Okay I'll work on that now. is this an updated mock up? the one i was looking at initially didn't have a top border at log out. I may be wrong.

**Comment by paulchrisluke** [comment]
@sansNoms this is updated, but  refer to the designs to be sure
