### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#229]
This is a design for when someone forgets their password and already requested a password reset #228 . 
Site visitors would be navigating to this page after clicking from their password reset email. 

### Desktop 
![image](https://user-images.githubusercontent.com/5694308/69473522-d9befb80-0de7-11ea-880b-5c5827c930ec.png)

This is immediately what they see when they are redirected from their password reset email. 

Once they fill in new passwords, their password is reset and the pop-up closes to show the home page.

### Mobile and Tablet

![image](https://user-images.githubusercontent.com/5694308/69473566-78e3f300-0de8-11ea-9863-b1cdd28e8f2e.png)

Design File: https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8237%3A0

**Comment by Cheanataly** [comment]
The previous "Reset Password" is redesigned and the following is the new design:

The design is new, but the flow of process is still same. Site visitors would be navigating to this page after clicking from their password reset email. 

**Desktop and Mobile**
![image](https://user-images.githubusercontent.com/34535916/70696634-b0aece00-1cf6-11ea-91f4-6e7cc256f2e6.png)


When the visitors click the reset link in their email, this page will be shown to them.
After they have reset their password, they will redirect to home page.

**Comment by paulchrisluke** [comment]
@Cheanataly the "yes I want to reset" design seems redundant to the button. Is there a reason we have a selector there? @Timboh56 hold on the programming of this for a sec want to review the ux

**Comment by Cheanataly** [comment]
@paulchrisluke There is the text above the design, said that "it needs the password reset confirmation".

**Comment by paulchrisluke** [comment]
Nataly Chea Julia says she's sorry and these were just her notes. The confirmation "successfully reset" should appear after you hit the reset password button in the form of a snackbar popup  https://material-ui.com/components/snackbars/
