### ISSUE TITLE
create "Your Upcoming Trips" page

### ISSUE THREAD

**Issue by Cheanataly** [whynotearth/hotel-website-vkirirom.com#232]
This is the sample page for "Your Upcoming Trips" page and below is the detail of what we want:

Here is the complete look of this page:
![image](https://user-images.githubusercontent.com/34535916/70974298-03fb9480-20da-11ea-9cc0-483115834b5e.png)

The top nav is the nav that we have already created
![Nav](https://user-images.githubusercontent.com/34535916/69600425-2a7e6080-1043-11ea-902c-54364862fd48.PNG)

![List_Trips](https://user-images.githubusercontent.com/34535916/69600520-78936400-1043-11ea-895a-6f78dd0dea4a.PNG)
After the top nav, there is the page title. The page title is H1.
Then, it contains list of cards which the card style is the same in "New Search Page". The list of the cards are the bookings that customer has booked from the resort.

![image](https://user-images.githubusercontent.com/34535916/70974251-e9c1b680-20d9-11ea-8857-e74a2d19dac1.png)

For the footer, we use the already created one.

**Comment by paulchrisluke** [comment]
@Cheanataly this needs to be much more detailed. See whynotearth/whynot.earth#36 for example. You want to give the developers everything so they know exactly what they need right when they see the issues. That includes links, screenshots, hex codes, etc.
