### ISSUE TITLE
create "Single Trip" page

### ISSUE THREAD

**Issue by Cheanataly** [whynotearth/hotel-website-vkirirom.com#233]
This is the sample of the page and the detail of the page:

The overlook of the page:
![image](https://user-images.githubusercontent.com/34535916/70976456-89814380-20de-11ea-9299-e7be177f5d33.png)

The nav is the one which is created.

![image](https://user-images.githubusercontent.com/34535916/69608163-66bcbb80-1059-11ea-8428-1ae31bf95b9d.png)
The right of the page is the confirm booking. The confirm booking contains the number of guests, check-in and check-out date, price and also the customer information. It also has other features:
- The pencil icon: it allows customers to modify their booking like change number of guests, check-in and check-out date, etc.
Use the booking flow #213 as the editing CMS. They are allowed to change the number of guests and the dates, but any other booking details require contacting vkiriom. Personal customer info can be changed in the "my profile" section instead. 

- Cancel Booking Button: The customer can cancel their booking. When the customer clicks the button, it will lead to another page to cancel their booking. The button is in this color (#EB5757).
.
![image](https://user-images.githubusercontent.com/34535916/69608923-f9118f00-105a-11ea-97e6-f1d6784283fc.png)
On the left of the page, it has content which listed (see the photo above):
The "Thank You!" text is H1
The "vKirirom Pine resort" text is H2 and the hex is F7B947
Apart from these two headlines, all the headline is H3.

The footer: use the already created one.

Design File: https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by paulchrisluke** [comment]
@Cheanataly this needs to be much more detailed. See https://github.com/whynotearth/whynot.earth/issues/36 for example. You want to give the developers everything so they know exactly what they need right when they see the issues. That includes links, screenshots, hex codes, etc.
