### ISSUE TITLE
Fix fonts and use design's font faces

### ISSUE THREAD

**Issue by mort3za** [whynotearth/hotel-website-vkirirom.com#235]
Current fonts are Helvetica and Oswald (google font, used in homepage big titles).

**Comment by mort3za** [comment]
@paulchrisluke  @bamboochow The current font is Helvetica as before (in vkirirom.com). If we need to change it, this is the time.

> Helvetica is NOT and has NEVER BEEN a standard or supplied Windows typeface.

It's better to use a web font, system fonts are not reliable.

**Comment by paulchrisluke** [comment]
New font is Montserrat 
![image](https://user-images.githubusercontent.com/5694308/70599951-0fa21380-1c21-11ea-8b40-6b6511c978ff.png)
![image](https://user-images.githubusercontent.com/5694308/70599986-25173d80-1c21-11ea-8843-174575de3242.png)
![image](https://user-images.githubusercontent.com/5694308/70599997-2c3e4b80-1c21-11ea-86ab-35f4d6c810a7.png)
![image](https://user-images.githubusercontent.com/5694308/70600018-35c7b380-1c21-11ea-8ae6-a503ec0fc870.png)
![image](https://user-images.githubusercontent.com/5694308/70600029-3ceec180-1c21-11ea-8eb9-9216623fc78b.png)
![image](https://user-images.githubusercontent.com/5694308/70600040-437d3900-1c21-11ea-9564-a266541c1386.png)
![image](https://user-images.githubusercontent.com/5694308/70600056-4c6e0a80-1c21-11ea-91ab-b5c763cad706.png)
