### ISSUE TITLE
Add Different Forms For Netlify

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#238]
![image](https://user-images.githubusercontent.com/5694308/69774295-1ca61800-11c8-11ea-8137-93aacb9792d7.png)

Add one form for each page category (events, blogs, etc etc)

**Comment by paulchrisluke** [comment]
@mort3za , I think we lost our forms on our sub pages like we used to have on pages like this: 

https://develop.vkirirom.com/listing/Coming-Soon-Grand-Opening-of-vKirirom-Garden-of-Wonder-in-September

what needs to be done to bring those back?

**Comment by mort3za** [comment]
@paulchrisluke Do you mean the contact form on the right side? I need a design flow for it to know what should I do exactly, we talked about them I think and the decision was disabling them for now.

**Comment by paulchrisluke** [comment]
@mort3za What's the time difference between adding the form on the right side of the page like we used to have for all pages except accomodations.

OR, adding the booking bar with a contact button in it that leads to contact page

**Comment by mort3za** [comment]
Changing the config of which form should be sent to which email address is changable from here: https://app.netlify.com/sites/cranky-nightingale-3731fc/settings/forms

**Comment by mort3za** [comment]
I use the field `name` in the resort response as form name (menu, experiences, ...)  
Some requests have a general name that should be changed in database. e.g. `menu` request has name of `search` here: https://stagingapi.whynot.earth/api/v0/pages/slug/vkirirom/menu?culture=en-US

**Comment by paulchrisluke** [comment]
I want to get away from using `name` if we can. Its kinda hacky and prone to user error since we hand type those titles in. Could we use `category` instead? It is the same, just safer. Here are the categories for vkirirom and which emails should be notified on form fill. We can make new forms in netlify to add these:


id | Name | email notify 1 | email notify 2 | email notify 2
-- | -- | -- | -- | --
1 | accommodations | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
2 | experiences | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
3 | events | sales@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
4 | blog | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
5 | food | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
6 | service | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
7 | lease | sales@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
8 | ecotourism | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
9 | landing | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
10 | home | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
11 | career | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
12 | story | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
13 | search | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
14 | checkout | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh
15 | contact | info@vkirirom.com | chris@whynot.earth | hicki.okamoto@kit.edu.kh

**Comment by mort3za** [comment]
@paulchrisluke Yeah, PR updated.

**Comment by paulchrisluke** [comment]
Approved to merge
