### ISSUE TITLE
Add "Accounts" Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#255]
### Desktop
This page is the "my accounts" page for users that log into vkirirom.com
![image](https://user-images.githubusercontent.com/5694308/70880614-29b26c00-1ffc-11ea-96c0-5ed7126d81c0.png)

Known information is already filled in in each of the info fields, and users can change it by clicking on input field and typing in new information. They must save in order to update info. 

If no info updated, "update info" button is inactive 

### Mobile
![image](https://user-images.githubusercontent.com/5694308/70880619-32a33d80-1ffc-11ea-8095-6073af7012ed.png)

Known information is already filled in in each of the info fields, and users can change it by clicking on input field and typing in new information. They must save in order to update info. 

If no info updated, "update info" button is inactive 

### Extra Info
Design: https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8237%3A2

**Comment by mort3za** [comment]
@paulchrisluke 
We no longer get the credit card info. Stripe handles it. will remove it if you agree

**Comment by paulchrisluke** [comment]
agree, will remove from design file as well @mort3za 

@Cheanataly , please remove the credit card info from this page.
