### ISSUE TITLE
Draw bed icon 

### ISSUE THREAD

**Issue by DaroDalya** [whynotearth/hotel-website-vkirirom.com#260]
Use idobe illustrator to draw the bed icon for single, double, queen and king size bed.
![image](https://user-images.githubusercontent.com/34526983/71071393-1f849f00-21af-11ea-9c42-3b7e48dc6014.png)

**Comment by paulchrisluke** [comment]
@bamboochow add these to our design fileand provide @mort3za with the icons

**Comment by bamboochow** [comment]
@DaroDalya Where do i get access to these icons?

**Comment by DaroDalya** [comment]
@bamboochow here is the drive link that nataly has upload all the icon set https://drive.google.com/drive/folders/1S2fLu_n38Rhzr4NMLt9Z7GYh6C4x4w4a

**Comment by paulchrisluke** [comment]
@DaroDalya see how the icon set here is a bit fatter with a slightly smaller stroke?

https://user-images.githubusercontent.com/34526983/71071393-1f849f00-21af-11ea-9c42-3b7e48dc6014.png

try and reduce your stroke a bit, and widen the "single" bed. on the version with two single beds, they should be straiter (wider) . Right now the single bed doesn't look too comfortable to lay on!

![image](https://user-images.githubusercontent.com/5694308/71226635-2cb89f80-230f-11ea-80a1-7cdb85ff471c.png)
