### ISSUE TITLE
vKirirom New Packages

### ISSUE THREAD

**Issue by sotheaYouk** [whynotearth/hotel-website-vkirirom.com#268]
I created 5 pages for our new 5 new packages and they are ready for review. You can find them in attached link below. @paulchrisluke 
1. vKirirom Pine Resort Eco Educational Tour Package 
id: 190 
release: Dec 25, 2019 
2. Bronzed Package of Happiness Family Trip for 2 Days and 1 Night at vKirirom Pine Resort
id: 191 
release: Dec 28, 2019 
3. Silver Package of Happiness Family Trip for 2 Days 1 and Night at vKirirom Pine Resort
id: 192 
release: Jan 1, 2020 
4. Golden Package of Happiness Family Trip For 2 Days and 1 Night at vKirirom Pine Resort
id: 193 
release: jan 4, 2019 
5. Group Tour Package For Solidarity and Cooperation Team For 2 Days 1 and Night at vKirirom Pine Resort
id: 194 
release: jan 8, 2019 
link to public: https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=550121964

**Comment by paulchrisluke** [comment]
there are some errors in the json, pinged you about it in discord @sotheaYouk

**Comment by bamboochow** [comment]
These have been added, sorry for not mentioning earlier @sotheaYouk

**Comment by sotheaYouk** [comment]
https://vkirirom.com/listing/vKirirom-Pine-Resort-Eco-Educational-Tour%20Package i dont see featured images of this one and i only see 1 featured image of the other 4 pages; there's supposed to be 5 for each page @bamboochow

**Comment by paulchrisluke** [comment]
@sotheaYouk Images are all good now, please double check

**Comment by sotheaYouk** [comment]
they all look good to me; however, i'll send them to mr. socheat to review. he might want to change some stuff. @paulchrisluke
