### ISSUE TITLE
Change Titles of Booking Flow

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#269]
### Previous Designs
Our original designs had simply H2 text as the title 
![image](https://user-images.githubusercontent.com/5694308/71395421-758e9200-2648-11ea-81ab-69d36d5f4790.png)

### New Design
We're adding an image and all header text will be H1 
![image](https://user-images.githubusercontent.com/5694308/71395393-58f25a00-2648-11ea-940f-c79bdbba4c0b.png)
![image](https://user-images.githubusercontent.com/5694308/71395408-63145880-2648-11ea-89b6-2e65475e9037.png)
![image](https://user-images.githubusercontent.com/5694308/71395418-6dceed80-2648-11ea-854c-50f671ea1e89.png)

This design is just like the original info card here: 
![image](https://user-images.githubusercontent.com/5694308/71395597-2dbc3a80-2649-11ea-95c1-dda642efd530.png)

Change all Booking Flow process with H2 titles to H2 with and image background and darker gradient
![image](https://user-images.githubusercontent.com/5694308/71395486-b5557980-2648-11ea-8c61-41f5d0619e0f.png)

Design: 
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8237%3A0

**Comment by mort3za** [comment]
I need the image files or Cloudinary links of those header images. @paulchrisluke

**Comment by paulchrisluke** [comment]
Choose Date: https://res.cloudinary.com/die9ji2vn/image/upload/v1577609316/Booking%20Flow/ChooseDate_bomyw8.png

Log In: https://res.cloudinary.com/die9ji2vn/image/upload/v1577609316/Booking%20Flow/LogIn_bl4sz3.png

Choose Guests: https://res.cloudinary.com/die9ji2vn/image/upload/v1577609316/Booking%20Flow/ChooseGuest_c9pgd1.png

For accomodations: Pull featured image from each accomodation page and use that as the image displayed for each accomodation
