### ISSUE TITLE
Remove Shuttle Booking from Flow

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#274]
Client asked to separate booking flow from shuttle booking

### Previous Designs 
Shuttle bus info was an option on the customer info page, and thank you page just had customer information on display 
![image](https://user-images.githubusercontent.com/5694308/70877632-dc7ccd00-1ff0-11ea-9699-3ae0e5dea791.png)
![image](https://user-images.githubusercontent.com/5694308/70877679-151ca680-1ff1-11ea-9101-527b85221c7b.png)
![image](https://user-images.githubusercontent.com/34535916/70972824-dfea8400-20d6-11ea-88a8-8de2ca006c24.png)

### Desktop
![image](https://user-images.githubusercontent.com/5694308/71538320-84808780-295b-11ea-9d7d-4b0db031e12b.png)
![image](https://user-images.githubusercontent.com/5694308/71538323-93673a00-295b-11ea-8030-f269194dab80.png)
Removed shuttle bus option on customer info page and added shuttle bus link button to Thank You page 
Change name of "Customer info" page to "Contact Info" 
Shuttle bus link: http://shuttlebus.vkirirom.com/login

### Mobile
![image](https://user-images.githubusercontent.com/5694308/71538333-cc9faa00-295b-11ea-95b8-39a9ccd474d3.png)
![image](https://user-images.githubusercontent.com/5694308/71538338-e0e3a700-295b-11ea-8593-f699ec49c80e.png)
Removed shuttle bus option on customer info page and added shuttle bus link button to Thank You page 
Change name of "Customer info" page to "Contact Info" 
Shuttle bus link: http://shuttlebus.vkirirom.com/login

### Design
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8237%3A0
Located on Sign in/Booking page

**Comment by bamboochow** [comment]
![image](https://user-images.githubusercontent.com/14948326/71711951-cdda4680-2e35-11ea-9c50-633dde0e46f2.png)
@mort3za  Just a minor spelling error here, otherwise all good
