### ISSUE TITLE
Mobile Booking Nav

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/hotel-website-vkirirom.com#283]
This is the mobile navigation specifically for the booking process steps review rules, contact info, payment. 
![image](https://user-images.githubusercontent.com/14948326/71713258-8eaef400-2e3b-11ea-838c-9fe8af7abc4c.png)

Normal Font: #B9BCC1
Accent Color: #E5B5CE
Shadow (same shadow also used elsewhere, named 4 dp): 
```
/* 4 dp */
box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2), 0px 4px 5px rgba(0, 0, 0, 0.12), 0px 1px 10px rgba(0, 0, 0, 0.2);
```

![image](https://user-images.githubusercontent.com/14948326/71713979-902deb80-2e3e-11ea-84c7-77d08bc4b61f.png)
![image](https://user-images.githubusercontent.com/14948326/71713955-79879480-2e3e-11ea-94dc-660ed233d414.png)
![image](https://user-images.githubusercontent.com/14948326/71713970-84dac000-2e3e-11ea-8932-2847631f5e8e.png)
Above is how the booking nav would be presented in each step of the booking process. 

### Design File
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by mort3za** [comment]
What is `Accent Color: #E5B5CE`? Where should I use this color?

**Comment by bamboochow** [comment]
@mort3za 
sorry, didn't write it specific enough
This color is used at this little line right here to indicate which step of the process the user is at:  
![image](https://user-images.githubusercontent.com/14948326/72660526-3ca8c980-3a0a-11ea-9fe4-3be1dedbfc64.png)
![image](https://user-images.githubusercontent.com/14948326/72660556-7679d000-3a0a-11ea-9937-561711c97388.png)
![image](https://user-images.githubusercontent.com/14948326/72660569-842f5580-3a0a-11ea-8d6d-cb762cf3adde.png)
![image](https://user-images.githubusercontent.com/14948326/72660572-8e515400-3a0a-11ea-8000-efeb865f8b4f.png)

**Comment by mort3za** [comment]
Has this any problem? @bamboochow

**Comment by bamboochow** [comment]
looks good @mort3za
