### ISSUE TITLE
Make Credit Card Line into 2 Rows

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/hotel-website-vkirirom.com#285]
### Current 
This is the current design for our credit card input 
![image](https://user-images.githubusercontent.com/14948326/71715415-d9cd0500-2e43-11ea-85cd-f422776ae0fd.png)

### Design 
We want a design where there's 2 lines: one for card number, the other one for expiration date and cvv, like in our design 
Desktop: 
![image](https://user-images.githubusercontent.com/14948326/71715497-244e8180-2e44-11ea-9ce9-dd413905257c.png)
Mobile: 
![image](https://user-images.githubusercontent.com/14948326/71715530-3defc900-2e44-11ea-978f-e2343dfde1aa.png)

Looks like stripe has some documentation for how to get some of these ui done 
https://stripe.dev/elements-examples/
https://github.com/stripe/elements-examples

### Design File 
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8237%3A0

**Comment by bamboochow** [comment]
![image](https://user-images.githubusercontent.com/14948326/72673049-ac1cc880-3a9f-11ea-98d8-ad77828b318b.png)
There's a little bit of an alignment issue right here 
![image](https://user-images.githubusercontent.com/14948326/72673053-b8a12100-3a9f-11ea-9856-d2984597378c.png)

Alignment should match our design 
![image](https://user-images.githubusercontent.com/14948326/72673055-dbcbd080-3a9f-11ea-9ace-fc39fc2d49fb.png)
where the edges have nothing sticking out

**Comment by mort3za** [comment]
directly pushed to `develop`. https://develop.vkirirom.com/booking/payment
