### ISSUE TITLE
Add address to payment page

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/hotel-website-vkirirom.com#288]
### Current
Our payment page right now does not have an address field 
![image](https://user-images.githubusercontent.com/34535916/70973503-5b006a00-20d8-11ea-8b6f-e103fc6a93d4.png)
![image](https://user-images.githubusercontent.com/5694308/68986995-7f59f400-0857-11ea-90df-c5f2bb240efd.png)

### Design
We are adding address fields to the payment page
![image](https://user-images.githubusercontent.com/14948326/71759747-6202e700-2ee4-11ea-8d94-e91e3ab26063.png)
![image](https://user-images.githubusercontent.com/14948326/71759750-6a5b2200-2ee4-11ea-93cb-ef2ed3dc040b.png)

With the same input design as everything else on the page 

Stripe has some info on their component ui 
https://stripe.dev/elements-examples/
https://github.com/stripe/elements-examples/

### Design File
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8237%3A0

**Comment by mort3za** [comment]
![image](https://user-images.githubusercontent.com/510242/72265220-596f8680-3631-11ea-8eda-9406e44f6004.png)

Stripe has the address, state, city and zip fields. I'll add them to stripe form.
