### ISSUE TITLE
Home Page Parallax and New Colors

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/hotel-website-vkirirom.com#289]
### Current
![image](https://user-images.githubusercontent.com/14948326/71759838-12251f80-2ee6-11ea-996b-fb73094880fe.png)
**I HATE THIS.** 

### Design
We are adding a parallax header image to our home page as well as changing the color scheme of the site to match the parallax effect 
![image](https://user-images.githubusercontent.com/14948326/71759868-94addf00-2ee6-11ea-83d5-d40ca86baa0c.png)

The new parallax effect will be identical to the whynot.earth parallax effect 
https://whynot.earth/

The image files are here: https://www.dropbox.com/sh/rfmk3bgzg39vdu4/AAAOcNi3QcgDwYj7n5WNrsmSa?dl=0

The logo is here: 
https://res.cloudinary.com/die9ji2vn/image/upload/v1560304571/vKirirom_logo_qm390e.jpg

New Background Color: 
![image](https://user-images.githubusercontent.com/14948326/71759898-5a910d00-2ee7-11ea-8e5a-7dc5eb566aea.png)

New Accent Color: #E5B5CE

### Design File 
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

### Related Pull Requests
https://github.com/whynotearth/whynot.earth/pull/5/commits/fa138d70329a0bef4997fd281190b508d609013a
https://github.com/whynotearth/whynot.earth/pull/5
https://github.com/whynotearth/whynot.earth/pull/4

**Comment by paulchrisluke** [comment]
@mort3za remember the logo should sit in the sky... something like this positioning:

![image](https://user-images.githubusercontent.com/5694308/71761550-460c3f00-2efe-11ea-9700-94376dab99c1.png)

**Comment by paulchrisluke** [comment]
@mort3za New Dropbox Link 
https://www.dropbox.com/s/4nibxbbueiov039/6.png?dl=0

**Comment by mort3za** [comment]
Couldn't find the logo file @paulchrisluke

**Comment by bamboochow** [comment]
@mort3za 
Below are new Cloudinary Links for all front page parallax assets: 
Logo: https://res.cloudinary.com/die9ji2vn/image/upload/v1578304830/Home%20Page/logo2_qoiy2d.png
Parallax Layers: 
1: https://res.cloudinary.com/die9ji2vn/image/upload/v1578304830/Home%20Page/1_edlfha.png
2: https://res.cloudinary.com/die9ji2vn/image/upload/v1578304830/Home%20Page/2_sswfon.png
3: https://res.cloudinary.com/die9ji2vn/image/upload/v1578304829/Home%20Page/3_dzzzbi.png
4: https://res.cloudinary.com/die9ji2vn/image/upload/v1578304829/Home%20Page/4_y2kccp.png
5: https://res.cloudinary.com/die9ji2vn/image/upload/v1578304830/Home%20Page/5_hqueja.png
6 (this is the layer with black as the connecting color):https://res.cloudinary.com/die9ji2vn/image/upload/v1578304829/Home%20Page/6-_Black_nt3cjt.png

The 6th layer (connecting to the rest of the site) should be fixed instead of parallaxing with the rest of the layers. Image shows what it's doing now. 
![image](https://user-images.githubusercontent.com/14948326/71811375-1b111f00-30a7-11ea-9dbd-39ebce79a0ac.png)

**Comment by paulchrisluke** [comment]
mobile assets, if these don't work well we can hash it out in discord.

https://www.dropbox.com/sh/3rkxsethv1mbzgw/AACKOXNQC0asHjHzwTNTh88Pa?dl=0

**Comment by paulchrisluke** [comment]
there is also a new mountain range in the dropbox file which has 100% opacity so the logo does not show through the mountains @mort3za

**Comment by paulchrisluke** [comment]
We have replaced the galaxy and the mountain layers for the desktop parallax on cloudinary, here are the new links for each 
1: https://res.cloudinary.com/die9ji2vn/image/upload/v1578391761/Home%20Page/1_xblbcz.png
3: https://res.cloudinary.com/die9ji2vn/image/upload/v1578391697/Home%20Page/3_s78ihj.png

We also got mobile assets for the parallax, links below: 
1: https://res.cloudinary.com/die9ji2vn/image/upload/v1578391904/Home%20Page/1_Mobile_nic1jq.png
2: https://res.cloudinary.com/die9ji2vn/image/upload/v1578391905/Home%20Page/2_Mobile_fbnhkc.png
3: https://res.cloudinary.com/die9ji2vn/image/upload/v1578391906/Home%20Page/3_Mobile_e9mhyt.png
4: https://res.cloudinary.com/die9ji2vn/image/upload/v1578391906/Home%20Page/4_Mobile_ftjfdh.png
5: https://res.cloudinary.com/die9ji2vn/image/upload/v1578391906/Home%20Page/5_Mobile_ozxcqz.png
6: https://res.cloudinary.com/die9ji2vn/image/upload/v1578391906/Home%20Page/6_Mobile_nogvnf.png

**Comment by mort3za** [comment]
@paulchrisluke  
Because of the type of cropping, I can't generate them automatically (needs human attention to crop). **So please provide all the other sizes**.  
These are our frontend breakpoints:  

![image](https://user-images.githubusercontent.com/510242/71907075-85e25900-3180-11ea-86a5-748f0bb841b5.png)

I need 600px width images for iPhone as the smallest size in our breakpoints (please don't delete the current mobile images until I'm sure that 600px works for iPhone)

**Comment by mort3za** [comment]
Responsive for iPhone added (PR updated).

**Comment by mort3za** [comment]
Seems the mobile version of layer 6 has an incorrect color (cropped from older version?).

**Comment by bamboochow** [comment]
Here are the new links for each set of cutoff point crops (with the right colors): 
**1264 px**: 
1: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452735/Home%20Page/1_-_1264_Crop_etah3p.png
2: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452735/Home%20Page/2_-_1264_Crop_oemckj.png
3: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452735/Home%20Page/3_-_1264_Crop_rzmbf7.png
4: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452734/Home%20Page/4_-_1264_Crop_b2si7p.png
5: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452735/Home%20Page/5_-_1264_Crop_j243x6.png
6: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452734/Home%20Page/6_-_1264_Crop_axf4bc.png

**960 px**: 
1: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452929/Home%20Page/1_-_960_Crop_oa7sit.png
2: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452931/Home%20Page/2_-_960_Crop_nmuzwk.png
3: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452928/Home%20Page/3_-_960_Crop_u8unwb.png
4: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452928/Home%20Page/4_-_960_Crop_yjllbe.png
5: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452928/Home%20Page/5_-_960_Crop_kxqi9o.png
6: https://res.cloudinary.com/die9ji2vn/image/upload/v1578452928/Home%20Page/6_-_960_Crop_yweblf.png

**600 px**: 
1: https://res.cloudinary.com/die9ji2vn/image/upload/v1578453084/Home%20Page/1_-_600_Crop_exoo15.png
2: https://res.cloudinary.com/die9ji2vn/image/upload/v1578453086/Home%20Page/2_-_600_Crop_ljuk1q.png
3: https://res.cloudinary.com/die9ji2vn/image/upload/v1578453084/Home%20Page/3_-_600_Crop_oi117l.png
4: https://res.cloudinary.com/die9ji2vn/image/upload/v1578453084/Home%20Page/4_-_600_Crop_lzo0qm.png
5: https://res.cloudinary.com/die9ji2vn/image/upload/v1578453084/Home%20Page/5_-_600_Crop_hv4pgh.png
6: https://res.cloudinary.com/die9ji2vn/image/upload/v1578453084/Home%20Page/6_-_600_Crop_dld0qh.png

**Comment by mort3za** [comment]
Updated version of this file, please: https://res.cloudinary.com/die9ji2vn/image/upload/v1578391906/Home%20Page/6_Mobile_nogvnf.png

> 376px of layer 6

**Comment by bamboochow** [comment]
Here you can have them all :D 
376 Crop: 
1: https://res.cloudinary.com/die9ji2vn/image/upload/v1578537679/Home%20Page/1_-_376_Crop_f3kohe.png
2: https://res.cloudinary.com/die9ji2vn/image/upload/v1578537679/Home%20Page/2_-_376_Crop_jurubz.png
3: https://res.cloudinary.com/die9ji2vn/image/upload/v1578537679/Home%20Page/3_-_376_Crop_hzx8pn.png
4: https://res.cloudinary.com/die9ji2vn/image/upload/v1578537679/Home%20Page/4_-_376_Crop_ojxrls.png
5: https://res.cloudinary.com/die9ji2vn/image/upload/v1578537679/Home%20Page/5_-_376_Crop_kwd38n.png
6: https://res.cloudinary.com/die9ji2vn/image/upload/v1578537678/Home%20Page/6_-_376_Crop_idycl2.png

**Comment by paulchrisluke** [comment]
looks great
