### ISSUE TITLE
Change ModuleHotel content to H2

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#298]
### Previous Design
Our current accomodation listing pages has this formatting and because of our database, some titles are H2 while others are H3 
![image](https://user-images.githubusercontent.com/5694308/71872485-2d469800-314f-11ea-825a-45bbe09565d8.png)

### What We Want 
Go into the ModulesHotel sheet and change every Markdown H3 to H2  
https://docs.google.com/spreadsheets/d/1nK15V2k0vu6Nyvt7pxbKeL5hlyItwaHsIScQzmeRmFI/edit#gid=1818329111

For example:  
![image](https://user-images.githubusercontent.com/5694308/71872579-71d23380-314f-11ea-8d2d-fa9fc53bd915.png)
the "###Shuttle bus" should be "##Shuttle Bus" 

After you fix it, highlight all cells that you've made changes to in the google sheet

**Comment by sotheaYouk** [comment]
done @paulchrisluke

**Comment by bamboochow** [comment]
This looks good, reminder to move things into "Review in progress" when you're done.
