### ISSUE TITLE
New Top Navigation

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#299]
### Previous Design 
![image](https://user-images.githubusercontent.com/5694308/71873319-74358d00-3151-11ea-87a6-e6db5d0a9d32.png)
Previous design had logo on the far left and elements on the right and is a static bar

### New Design
Our new design has a centered navigation, with the new logo at the center, with an increased thickness to the background bar and added shadow
![image](https://user-images.githubusercontent.com/5694308/71873368-8b747a80-3151-11ea-9783-a6bac9e26d20.png)
![image](https://user-images.githubusercontent.com/5694308/71873399-9e874a80-3151-11ea-93a4-6c3aee60a59e.png)
**Shadow**: 
![image](https://user-images.githubusercontent.com/5694308/71873845-cdea8700-3152-11ea-86a7-276a6de54809.png)
This 4dp shadow is used elsewhere, so make sure it is a global feature

**Logo**: https://res.cloudinary.com/die9ji2vn/image/upload/v1578304830/Home%20Page/logo2_qoiy2d.png

The nav structure remains the same. The log in/profile switch should still be there 
![image](https://user-images.githubusercontent.com/5694308/71873680-5f0d2e00-3152-11ea-9e4c-b090c6858028.png)
All the text should line up at the bottom

This new top nav bar comes with a scrolling animation, we want it to be identical to this site: 
https://www.elegantthemes.com/preview/Divi/interior/
Where it is not visible but appears once you scroll to a certain point

### Design
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=8585%3A7175

**Comment by bamboochow** [comment]
![image](https://user-images.githubusercontent.com/14948326/72801324-3887e080-3c84-11ea-97e0-a0c448be6515.png)
@mort3za this looks good, but we're switching the placement of menu and experience to make the top nav look more balaced

**Comment by mort3za** [comment]
New requested change applied.

**Comment by paulchrisluke** [comment]
should only be fixed on the home page. The rest of the pages it can just be at the top. It takes up too much space with the fixed booking bar as well on mobile.

**Comment by paulchrisluke** [comment]
also the nav should trigger when the logo disapears as if it just slid into the nav bar. The example url the nav comes in once the logo disapears: https://www.elegantthemes.com/preview/Divi/interior/

![image](https://user-images.githubusercontent.com/5694308/72863485-56485a80-3d03-11ea-8aae-a1d8ffe82399.png)
