### ISSUE TITLE
Change the entire website background color

### ISSUE THREAD

**Issue by Cheanataly** [whynotearth/hotel-website-vkirirom.com#301]
Previously, the background color is the linear of #00243E and #003E3A.

Due to the parallax picture and we want to make the color in the website to be matched. So, we have changed the color of the background.

The new background color is the combination of two linear which are:
**Background Code**
background: linear-gradient(180deg, #010101 0%, rgba(20, 21, 39, 0) 100%), linear-gradient(171.85deg, #141527 9.01%, #3A3B5E 94.56%);

Here are some pages with new background color:
![image](https://user-images.githubusercontent.com/34535916/71964823-0bbddd00-3231-11ea-8d76-168119f7cb94.png)

![image](https://user-images.githubusercontent.com/34535916/71964865-21cb9d80-3231-11ea-82e7-59ca2c4b72c9.png)

For more details:
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by mort3za** [comment]
This is done :thinking:
