### ISSUE TITLE
Add HTML to database

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#302]
In preparation for language additions, we want to change the formatting of the database entry so that we can switch between languages.

For **all entries with both Khmer and English**, edit each entry in the database like the examples below: 
```
<p class="en">Essentials (towels, bed sheets, soap, toilet paper, and pillows), Wifi, Cloth hanger rack, Fan, Coffee/Tea, Safe Box</p>

<p class="kh">សំភារៈប្រើប្រាស់ចាំបាច់ (កន្សែង, ស្រោមពូក, សាប៊ូ, ក្រដាសជូតបង្គន់ និងខ្នើយ), ប្រព័ន្ធ Wifi, កន្លែងដាក់សំលៀកបំពាក់, កង្ហារ, កាហ្វេ/តែ, ទូរសុវត្ថិភាព</p>
```
Where it used to look like this: 
```
Essentials (towels, bed sheets, soap, toilet paper, and pillows), Wifi, Cloth hanger rack, Fan, Coffee/Tea, Safe Box
សំភារៈប្រើប្រាស់ចាំបាច់ (កន្សែង, ស្រោមពូក, សាប៊ូ, ក្រដាសជូតបង្គន់ និងខ្នើយ), ប្រព័ន្ធ Wifi, កន្លែងដាក់សំលៀកបំពាក់, កង្ហារ, កាហ្វេ/តែ, ទូរសុវត្ថិភាព
```
For all entries in ModuleHotel and Public: 
Module Hotel: https://docs.google.com/spreadsheets/d/1nK15V2k0vu6Nyvt7pxbKeL5hlyItwaHsIScQzmeRmFI/edit#gid=1938788442
Public: https://docs.google.com/spreadsheets/u/2/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=550121964

**Comment by sotheaYouk** [comment]
all done. please check @paulchrisluke
