### ISSUE TITLE
Footer Language Toggle

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#308]
This is the language toggle option in the  footer of our vkirirom site 
![image](https://user-images.githubusercontent.com/5694308/72147948-414dfc00-33d2-11ea-83ed-6dd26e8aa852.png)
![image](https://user-images.githubusercontent.com/5694308/72147960-47dc7380-33d2-11ea-8ab1-0eff35a53f39.png)
![image](https://user-images.githubusercontent.com/5694308/72148428-59724b00-33d3-11ea-9364-58c66011b7b9.png)

Default active language will be English. 
The chosen language will be "circled" by a rounded square in the color of our pink accent color (#E5B5CE)

Icons included just in case. However, if there is a preexisiting icon set already loaded (vuetify?) use those instead 
Khmer Flag: https://res.cloudinary.com/die9ji2vn/image/upload/v1578654272/website-static/icon/Khmer_Flag_nstz23.png
US Flag: https://res.cloudinary.com/die9ji2vn/image/upload/v1578654272/website-static/icon/image_7_eiwawb.png

When clicking/tapping the other flag, the site will change to the other langauge. 

### Design: 
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by paulchrisluke** [comment]
should be site wide, like on our listing pages as well: https://develop.vkirirom.com/listing/Bell-Tent @mort3za

**Comment by mort3za** [comment]
@paulchrisluke toggler is inside footer so it's site wide, where we don't have it?

![image](https://user-images.githubusercontent.com/510242/72438770-ca8e7580-37ba-11ea-84fa-5963db5681db.png)

**Comment by bamboochow** [comment]
@paulchrisluke @mort3za 
This toggling looks like its based on the html classes we added into the page descriptions. We just split up the hotel module database to its translation pages, so that needs to be added in as well 
https://github.com/whynotearth/hotel-website-vkirirom.com/issues/322

**Comment by paulchrisluke** [comment]
yes new issue @bamboochow
