### ISSUE TITLE
Add header to search pages

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#311]
### Previous 
Right now our search pages only show options and not any copy or any header 
![image](https://user-images.githubusercontent.com/5694308/72151576-259b2380-33db-11ea-98f7-6a782d0abbd9.png)

### Current Design
![image](https://user-images.githubusercontent.com/5694308/72152312-2fbe2180-33dd-11ea-8d66-747a3fee5d0f.png)

Add static full size header image with centered H1 title in our accent color (#E5B5CE) and copy in normal text to all of our search pages. Copy will be added to database in each page as the page descriptions
![image](https://user-images.githubusercontent.com/5694308/72152233-fc7b9280-33dc-11ea-8279-e04d5feedf86.png)

Have the header image adjust full width dynamically to all window sizes 
header image: https://res.cloudinary.com/die9ji2vn/image/upload/v1578657961/Home%20Page/Full_n5ibke.png

### Design File
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by paulchrisluke** [comment]
also change background color to purple one @mort3za

**Comment by mort3za** [comment]
This request returns 404: https://stagingapi.whynot.earth/api/v0/pages/slug/vkirirom/accommodations

I use it but we need to fill data in the database. @paulchrisluke

**Comment by paulchrisluke** [comment]
@bamboochow we can place the cloudinary image in the database if we make a search pages?

**Comment by paulchrisluke** [comment]
This is according to this deploy preview 
https://deploy-preview-327--cranky-nightingale-3731fc.netlify.com/search/accommodations
![image](https://user-images.githubusercontent.com/5694308/73147617-d5b2a100-40ea-11ea-8136-7ad38e01b7c9.png)
The header is showing up but the title for the accomodation page shows "search" instead of "accomodations" 

![image](https://user-images.githubusercontent.com/5694308/73147658-114d6b00-40eb-11ea-8ad1-8bdd110b6e79.png)
https://deploy-preview-327--cranky-nightingale-3731fc.netlify.com/search/food
https://deploy-preview-327--cranky-nightingale-3731fc.netlify.com/search/experiences
"Menu" and "Experiences" show blank header images with no title at all 

I also changed the image to be a little shorter 
https://res.cloudinary.com/die9ji2vn/image/upload/v1580094146/Home%20Page/full_image_wqohcr.png
links are changed in the database, but I think this was hardcoded in

**Comment by mort3za** [comment]
@paulchrisluke new image's width is 1440px. It's blurry in 1920x1080.  
These types of cropping should be made in frontend using cloudinary transformations.

**Comment by paulchrisluke** [comment]
https://deploy-preview-342--cranky-nightingale-3731fc.netlify.com/search/experiences is not showing any header image or title 
![image](https://user-images.githubusercontent.com/5694308/73232804-2099ea80-41b7-11ea-93e6-e1121db8fb3e.png)

**Comment by mort3za** [comment]
@paulchrisluke experiences does not exist in database, should change it from experience to experiences.
