### ISSUE TITLE
Add sass version of Vuetify, lint fix all files, more

### ISSUE THREAD

**Issue by mort3za** [whynotearth/hotel-website-vkirirom.com#312]
- use sass version of vuetify and modify it's variables
- lint fix all files
- update packages
- remove bootstrap usages (except media query mixins)
- cleanup unused files
- use `hidden-*` classes instead of `d-none d-sm-block/flex`
- remove cypress (was unused, can be added again easily)

What should be reviewed?  
There is a chance that colors have changed somewhere accidentally, although I tried to keep it bugless.

**Comment by paulchrisluke** [comment]
will check colors in a bigger qa check before release
