### ISSUE TITLE
Google Tag Manager install bug

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#318]
Google analytics is currently collecting data, but is not showing as installed correctly in multiple tests.

Google search console:
![image](https://user-images.githubusercontent.com/5694308/72400031-7bc0eb80-377a-11ea-8beb-a78fdd690eed.png)

Oddly enough, facebook is showing installed correctly and it is being fired THROUGH GTM...

![image](https://user-images.githubusercontent.com/5694308/72400119-ca6e8580-377a-11ea-8ab3-a7a7f771cff1.png)
![image](https://user-images.githubusercontent.com/5694308/72400128-d3f7ed80-377a-11ea-93be-a3075447ce1c.png)

need to figure out why google analytics is not showing as installed so we can connect google search console and other products

**Comment by paulchrisluke** [comment]
Resolved. Dunno what @mort3za did tho

**Comment by mort3za** [comment]
I had written a condition to print gtm script tag only in production environment. I just removed that condition.  
The script tag was printed in source of develop.vkrirom.com, I don't know why that condition wasn't working
