### ISSUE TITLE
create and load brighter amenities icons

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#33]

**Comment by paulchrisluke** [comment]
probably brighter

**Comment by paulchrisluke** [comment]
Essentials (towels, bed sheets, soap, toilet paper, and pillows)
Wifi
TV
Closet
Fan
Sofa
Coffee/Tea
Desk/workplace
Safe Box


current amenities

**Comment by bamboochow** [comment]
this went from "brighter icons" to "Julia gets frustrated and redesigns the whole damn architecture and components of the listing page"
Oops. 

- added icons for amenities 
- realign all sections 
- New button for listing page
- Standardize section heading fonts
- Standardize review formats

@atharva3010

**Comment by paulchrisluke** [comment]
@bamboochow hair dryer icon, after you update please tag Atharva for change

https://icons8.com/icon/70/hair-dryer

**Comment by bamboochow** [comment]
@atharva3010 added hair dryer icon
