### ISSUE TITLE
Update Footer

### ISSUE THREAD

**Issue by Cheanataly** [whynotearth/hotel-website-vkirirom.com#334]
Both Footer (Desktop and Mobile version) is updated by adding another footer link (Blog) in Learn sector.

You can see the design:

**Desktop Design**
![image](https://user-images.githubusercontent.com/34535916/72875088-1ba3e980-3d26-11ea-9597-a1fa6acfb4f9.png)

**Mobile Design**
![image](https://user-images.githubusercontent.com/34535916/72875123-34ac9a80-3d26-11ea-8f0f-7bc35fe5439a.png)

When the Blog is clicked, it will lead to blog page which contains the list of blogs.

More details:
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by paulchrisluke** [comment]
@mort3za https://develop.vkirirom.com/search/blog
Added "blog" search page into database but the search page is not currently connected to anything blog posts

Connect the blog search page to all the pages in the "blog" categories (category id #4) so the page will be populated with blog posts
