### ISSUE TITLE
dark mode the calendar

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#35]
may need to build a custom component rather than use existing, possibly a good student job.

**Comment by paulchrisluke** [comment]
@Cheanataly since you are redoing the site in a design system, it would make sense to do this task at the same time.

**Comment by Cheanataly** [comment]
@paulchrisluke I am not really sure what I have to do with this task. Can you clarify it?

**Comment by paulchrisluke** [comment]
@Cheanataly currently our calendar is light, white background. We want to make it dark to match the rest of the site

**Comment by Cheanataly** [comment]
@paulchrisluke I think you have already done it and I just modified the size based on the version.
