### ISSUE TITLE
Update "Logo sets"

### ISSUE THREAD

**Issue by Cheanataly** [whynotearth/hotel-website-vkirirom.com#358]
The logo of vKirirom Pine resort has updated. The below is the google drive folder which contains the new logo in different size that has already resized and format:

https://drive.google.com/drive/folders/1O7jVjM2HwY6_IXnDAX5LN__5jylgzWAY?usp=sharing

**Comment by paulchrisluke** [comment]
https://www.dropbox.com/sh/59pbca8elnhjek1/AACqUuxDiKnygfc1YU_yNDYha?dl=0&fbclid=IwAR1uF6ZEx-b8EkPYpYZmIr56hr1b6INTUuKEKwJG6hJRBDwoEd_bgFbChS4 

new icons with white background
