### ISSUE TITLE
Integrate ecommerce booking with stripe

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#36]
this can integrate with existing stripe setup in meredith core:
https://github.com/whynotearth/Meredith

will probably need to work @StrangeWill with tokens and such. Design files pending.

Consider that I want all of these data tied to the singular meredith database/api. All sites built on meredith api should share user data.

**Comment by atharva3010** [comment]
WIP

**Comment by paulchrisluke** [comment]
completed
