### ISSUE TITLE
splash screen to allow site to load

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#369]
Show logo on background color `141527`. remove after page load (or timer, dont know which is better) We want to the page to be fully loaded first.

https://miro.medium.com/max/540/1*TD9Grbgmcblh9EmeEiLcWg.gif

https://uxdesign.cc/building-the-perfect-splash-screen-46e080395f06

**Comment by mort3za** [comment]
Note to myself:  
Useful tool for iOS: https://appsco.pe/developer/splash-screens  
An article for PWAs on iOS: https://www.netguru.com/codestories/few-tips-that-will-make-your-pwa-on-ios-feel-like-native
