### ISSUE TITLE
Change description in camping listing page and add new description for all the accommodation page 

### ISSUE THREAD

**Issue by DaroDalya** [whynotearth/hotel-website-vkirirom.com#382]
change the word "Bed" to "Mattress"
![image](https://user-images.githubusercontent.com/34526983/73640112-4dab3900-46a0-11ea-9b39-7b4d4ee7c704.png)
and include this information in all accommodation
![image](https://user-images.githubusercontent.com/34526983/73640179-63b8f980-46a0-11ea-8594-f936c558dddd.png)

**Comment by DaroDalya** [comment]
make a change in AmenityTranslation 
https://docs.google.com/spreadsheets/d/1nK15V2k0vu6Nyvt7pxbKeL5hlyItwaHsIScQzmeRmFI/edit#gid=278434314
make a change in description 
https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=550121964
@paulchrisluke

**Comment by paulchrisluke** [comment]
@mort3za The "beds" need to be changed to "mattress" for the camping listing page 
![image](https://user-images.githubusercontent.com/5694308/73715170-a7197380-4745-11ea-8256-97868a5e8a14.png)

https://vkirirom.com/listing/Camping

This is hotel-website-vkirirom.com/src/views/ListingPage.vue, line 64 - 87
```
  <v-row>
              <v-col cols="12" :md="shouldShowContactForm ? 7 : 12">
                <!-- x double / x twin beds -->
                <v-row
                  no-gutters
                  class="flex-column light--text mb-4"
                  v-if="resort && resort.modules && resort.modules.hotel && resort.modules.hotel.roomTypes.length > 0"
                >
                  <v-col cols="12">
                    <div class="d-flex align-center">
                      <v-icon size="30" color="light" class="mr-2">hotel</v-icon>
                      <span class="mr-1" v-for="(roomType, index) in resort.modules.hotel.roomTypes" v-bind:key="index">
                        <span class="mr-1">
                          {{ roomType.beds[0].count }}
                          {{ roomType.beds[0].type }}
                        </span>
                        <span class="mr-1" v-if="index != resort.modules.hotel.roomTypes.length - 1">
                          /
                        </span>
                      </span>
                      <span>bed(s)</span>
                    </div>
                  </v-col>
                </v-row>
```

**Comment by mort3za** [comment]
I don't see any roomtype info in API for camping page, should I create "3 LargeTwin / ..." info by hard coding it?
