### ISSUE TITLE
Add Markdown for Accomodation Pages 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#383]
We have added markdown compatible text for Accomodation page content into the database
![image](https://user-images.githubusercontent.com/5694308/73652918-9b349f80-46ba-11ea-898d-bd66ec0624cd.png)

However, our text currently looks like this: 
![image](https://user-images.githubusercontent.com/5694308/73652993-cd460180-46ba-11ea-94b8-56b7bffbc8fe.png)

Where amenities should show as a bullet point list 
![image](https://user-images.githubusercontent.com/5694308/73653045-e9e23980-46ba-11ea-8963-3171777e3463.png)

Also, Cancellation Policy and Shuttle Bus Information have titles that are also using Markdown 
![image](https://user-images.githubusercontent.com/5694308/73653189-36c61000-46bb-11ea-87ca-db4f721c1828.png)
![image](https://user-images.githubusercontent.com/5694308/73653212-47768600-46bb-11ea-8844-baa797d5b581.png)

Where it should look something like this (same H2 title font as "amenities" "space" "location" 
![image](https://user-images.githubusercontent.com/5694308/73653266-6412be00-46bb-11ea-94d5-8db266277b04.png)

https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by mort3za** [comment]
Did you tested those texts on an online markdown editor? I see the list items in amenities but it seem that that text is not markdown standard, for example this is what I get in API:

```
- Essentials (towels, bed sheets, soap, toilet paper, and pillows), Wifi, Cloth hanger rack, Fan, Coffee/Tea, Safe Box\n- swimming pool (except camping)\n- rates are inclusive of daily breakfast (except camping)\n- complimentary welcome drink up on guest arrival. \n- daily complimentary drink water and coffee/tea in all guest rooms. (except camping)\n- complimentary internet access Wi-Fi Ticket for 24 hours if customers stay from one night and 2 hours at Pine View Kitchen for a day trip customer.\n- All rates are net and quoted in US dollar with non-commissionable\n
```

If you copy paste it in GitHub comment editor, you should see the desired result in preview tab. the problem is `\n` I think that is not supported in MD.

**Comment by mort3za** [comment]
There is a nice online editor here https://stackedit.io/app

**Comment by mort3za** [comment]
Sorry, there was an option in our markdown package to read `\n`. You don't need to do anything.

**Comment by mort3za** [comment]
@paulchrisluke Here is a table that don't render correctly: https://vkirirom.com/listing/Thrill-Activities

To fix it, just add another `Enter` (same `\n`) after `<p>` tag.  
`<p class=\"en\">\n||| \n|-|-| \n|Bike rental...` should be `<p class=\"en\">\n\n|||...`

**Comment by paulchrisluke** [comment]
@sotheaYouk @DaroDalya , see comment above. Need to reformat your price tables for food.... it may be easier to display the content in something like:

```
Bike Rental. . . . . . . . . . . . . . . $15
Chicken . . . . . . . . . . . . . . . . . $8
```

instead of using a table in markdown

**Comment by DaroDalya** [comment]
Reformat the price table is done. 
https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=550121964
I have highlighted the column that I've made a change in orange.
pls check @paulchrisluke

**Comment by DaroDalya** [comment]
when I write the content in the markdown editor, it is working fine but when I copy from the google sheet and paste it in the editor again the line does not break down properly. Do I have to add \n in each line? @mort3za 
when I write the content directly in the editor 
![image](https://user-images.githubusercontent.com/34526983/74095877-8aa47f00-4b29-11ea-87d6-439ff758b18a.png)
and I when copy it from the google sheet 
![image](https://user-images.githubusercontent.com/34526983/74095895-cdfeed80-4b29-11ea-994a-93614387e699.png)

**Comment by mort3za** [comment]
Only where you have `<p>` or closing p insert **two** break lines (inside html tag).

**Comment by mort3za** [comment]
Test a small part of page with this way on the website, if it worked continue editing other parts.

I tested it with hard coded content and it is working

**Comment by paulchrisluke** [comment]
There is something weird going on with the description, specifically with language toggle 

Here is an example: 
This is what's currently in the database for the Japanese menu: 
![image](https://user-images.githubusercontent.com/5694308/74098662-5478f680-4b4d-11ea-88a4-5c6c730fdddb.png)
This is what currently shows on the page: 
![image](https://user-images.githubusercontent.com/5694308/74098669-5e025e80-4b4d-11ea-9277-07d46157a12f.png)
where the Khmer description is not visible on English toggle, but does show a few items in khmer (not all)
![image](https://user-images.githubusercontent.com/5694308/74098683-8722ef00-4b4d-11ea-96c8-e07c25c2e0af.png)
and the Khmer toggle shows the description, but only under a few items in English

**Comment by paulchrisluke** [comment]
We should probably move the language toggle to a backend function.. we can
add an issue for that jn Meredith core.

**Comment by sotheaYouk** [comment]
Menus are displayed in both English and Khmer and if I select English, the description is shown in English, same as if I choose Khmer. 

Desktop: 
![image](https://user-images.githubusercontent.com/34526910/74333324-4aaff700-4dca-11ea-9586-6979f7557fc5.png)
![image](https://user-images.githubusercontent.com/34526910/74333452-8f3b9280-4dca-11ea-846f-d428e93fae3e.png)

Mobile:
![image](https://user-images.githubusercontent.com/34526910/74333517-abd7ca80-4dca-11ea-945b-41846c7bf19f.png)
![image](https://user-images.githubusercontent.com/34526910/74333529-b2664200-4dca-11ea-813f-ab4b934ca13c.png)

Also, notice how the name and price are not on one line? It looks kinda weird to me

**Comment by paulchrisluke** [comment]
@DaroDalya did you reformat this text to work as we discussed in discord today? If so we will change it the database and close this issue

**Comment by DaroDalya** [comment]
@paulchrisluke Yes, I have reformated it to this.
![image](https://user-images.githubusercontent.com/34526983/74422642-81951400-4e81-11ea-9a9c-dad4bc1f4c27.png)
I highlight the row I make a change in orange color.

**Comment by paulchrisluke** [comment]
@DaroDalya I'm going to do this today, the only change I need to make is to the food pages on the public database correct?

**Comment by DaroDalya** [comment]
@paulchrisluke also some experience listing page that has table format too.

**Comment by paulchrisluke** [comment]
@DaroDalya @mort3za we replaced the data in the database, can you please check? The Khmer and english are both showing at the same time

**Comment by mort3za** [comment]
> @DaroDalya @mort3za we replaced the data in the database, can you please check? The Khmer and english are both showing at the same time

Please provide a link to problematic page. Also, I think the optimized way to solve this issue is to test everything before massively updating database.

**Comment by paulchrisluke** [comment]
https://vkirirom.com/listing/Western

**Comment by paulchrisluke** [comment]
https://vkirirom.com/listing/Healthy
https://vkirirom.com/listing/Khmer
https://vkirirom.com/listing/Western
https://vkirirom.com/listing/Chinese-and-Thai
https://vkirirom.com/listing/Indian
https://vkirirom.com/listing/Japanese
https://vkirirom.com/listing/Desserts

https://vkirirom.com/listing/Family-Activities
https://vkirirom.com/listing/Thrill-Activities
https://vkirirom.com/listing/Team-Building-Activities
https://vkirirom.com/listing/Nature-Tours-and-Trekking-Activities
https://vkirirom.com/listing/Great-Photo-Opportunities
https://vkirirom.com/listing/Study-Tours-for-KIT-and-Ecotourism

Above are the pages that currently shows both Khmer and English. The same language toggle issue persists 
![image](https://user-images.githubusercontent.com/5694308/75000143-1f936a80-5490-11ea-880f-27effbcb07f5.png)
Where parts of the other language's content (but not all) are shown for either toggle. 

However, the issues outlined in this specific issue has been resolved, so the language toggle issue will be described in a separate issue, and this markdown issue will be closed and resolved.
