### ISSUE TITLE
change database for images and json

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#399]
We have a lot of cloudinary custom api stuff in our image urls. Please remove that from all image urls and just use the regular cloudinary link.

(we will apply the custom api stuff on the front end automatically)

Also, we added the page title AFTER the site name before. Please switch it to be BEFORE the site name... so like this:

Home | vKirirom Pine Resort

**Comment by sotheaYouk** [comment]
all done

**Comment by paulchrisluke** [comment]
@bamboochow please review and add to database. once done, we can move on #365
