### ISSUE TITLE
Add Description to Home page

### ISSUE THREAD

**Issue by Cheanataly** [whynotearth/hotel-website-vkirirom.com#421]
We have updated the Home page by adding the description below the parallax image.

Here is the description:
![image](https://user-images.githubusercontent.com/34535916/74423149-5ced6c00-4e82-11ea-901b-3df8aac582cf.png)

For description, it has:
- Headline: Font size is H1 and the font-color is #E5B5CE;
- description: Font size is paragraph (20px) and the font-color is #B9BCC1;
The font-style is Montserrat.

This is the overview of Home page:
![image](https://user-images.githubusercontent.com/34535916/74423205-742c5980-4e82-11ea-9ca5-91bd530566c7.png)

For more detail:
https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=0%3A1

**Comment by mort3za** [comment]
I used font-size 16 for body text because other pages have that font-size now. We need another issue to update all font-sizes and line-heights based on design changes.
