### ISSUE TITLE
convert camping to small medium big indivitual accomodations

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#430]
We are going to be splitting our "camping" page into three seperate pages

"small camping" 
"medium camping"
"big camping"

Please re-write unique descriptions, keywords, images, amenties, etc. for each of these three different pages, and let me know for review after.

After review, I will have you upload to the database.

If you can, please get to this quickly

**Comment by DaroDalya** [comment]
@paulchrisluke here is the link of the description of the 3 camping page.  please check it. https://docs.google.com/document/d/1zmo0xb4H8WMsiNNl2TiCRH72OYCBlhKCmcx5W-JJN7g/edit?usp=sharing

**Comment by paulchrisluke** [comment]
this is looking good. please get pictures, and other content needed and update the database to be ready for review.
