### ISSUE TITLE
English/Khmer language toggle

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#435]
### Issue
There is some issue with the content presented on different toggles with the language button, This issue is present on all "Menu" pages and "Experiences" pages

Here is an example: 
This is what's currently in the database for the Japanese (https://vkirirom.com/listing/Japanese) menu: 
![image](https://user-images.githubusercontent.com/5694308/75000525-29699d80-5491-11ea-85dd-a79cea02d62c.png)
This is what currently shows on the page: 
![image](https://user-images.githubusercontent.com/5694308/75000539-37b7b980-5491-11ea-8396-22b0b0e80f70.png)
where the Khmer description is not visible on English toggle, but does show a few items in khmer (not all)
![image](https://user-images.githubusercontent.com/5694308/75000591-5ae26900-5491-11ea-9493-d836752231d2.png)
and the Khmer toggle shows the description, but only under a few items in English

### Fix
Please fix the language toggle so that clicking English will only show English content and Khmer only shows Khmer 
so the Japanese food page (https://vkirirom.com/listing/Japanese) should look like this on Khmer toggle 
![image](https://user-images.githubusercontent.com/5694308/75000776-ecea7180-5491-11ea-818b-e2667d997bfe.png)
and like this on English toggle
![image](https://user-images.githubusercontent.com/5694308/75000870-42268300-5492-11ea-9f1d-80f4f0349959.png)

### Related Issues 
#317 #383 #308

**Comment by mort3za** [comment]
The correct way is using **div** tag because of the markdown standard. I fixed the data of page https://vkirirom.com/listing/Japanese  
All the spaces in the below example are important. Some lines have two space characters at the end of line, Also new lines inside HTML tags are important.

```
<div class="en">  

Try some Japanese favorite dishes such as yakitori skewered chicken and chicken katsu.  

</div>
<div class="en">

Chicken Katsu | $7.00  

Skewered Chicken Yakitori | $6.00  

Chicken & Egg Rice | $6.00  

</div>
<div class="kh">  

សាកល្បងមុខម្ហូបដែលអ្នកចូលចិត្តនៅជប៉ុនដូចជាសាច់មាន់យ៉ាគីតូរីចង្កាក់ និងសាច់មាន់ katsu ។  

</div>
<div class="kh">

មាន់បំពងកាតសុ | ៧ ដុល្លារ  

សាច់មាន់យ៉ាគីតូរីចង្កាក់ | ៦ ដុល្លារ  

បាយមាន់ស្រូបទឹកស៊ុបជប៉ុន | ៦ ដុល្លារ  

</div>
```

The problem with toggle language is you use `\n` to create a new paragraph inside a paragraph, and the new paragraphs don't have the language code, so these paragraphs are visible on both languages.

**Comment by mort3za** [comment]
If you want to continue using `<p class="kh/en">` tag, be sure to add `<p class="kh/en">` to all lines.  
By using p tag, you can't use markdown inside it, e.g. bolding. So that's why I recommend using div instead.  
`\n` will generate paragraphs automatically.

**Comment by paulchrisluke** [comment]
@DaroDalya Please update all descriptions in ModuleHotel and Public so that we are using <div class"kh/en"> on all of them in the database. 
https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit#gid=1109287103
https://docs.google.com/spreadsheets/d/1nK15V2k0vu6Nyvt7pxbKeL5hlyItwaHsIScQzmeRmFI/edit#gid=1067475989
