### ISSUE TITLE
SEO, add sitemap.xml

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#44]
https://app.neilpatel.com/en/seo_analyzer/site_audit?domain=cranky-nightingale-3731fc.netlify.com&view=errors

- add sitemap
- this still says we don't see a h1, heading, which is strange [bug]?
- disregard title being short, we can change that
- add meta description (should come from the listing page description)

**Comment by atharva3010** [comment]
I have removed the redundant h1's from the home page. Now, only the header image contains h1.

**Comment by atharva3010** [comment]
Meta description is also added.

**Comment by atharva3010** [comment]
I am currently running into configuring the sitemap from the client site.

**Comment by paulchrisluke** [comment]
this may make more sense to generate at a server level... @StrangeWill ?

**Comment by atharva3010** [comment]
Sitemap added, meta configured
