### ISSUE TITLE
Move login flow to after checkout

### ISSUE THREAD

**Issue by mort3za** [whynotearth/hotel-website-vkirirom.com#448]
https://github.com/whynotearth/meredith-core/issues/87

**Comment by mort3za** [comment]
@paulchrisluke I created a basic dialog for connecting accounts, but as you said the design is not finished, please update the design of that dialog. Also, There should be a way to open the dialog manually I think.

<img src="https://user-images.githubusercontent.com/5694308/74733702-7118db00-527f-11ea-864d-c16648839773.png" />

**Comment by paulchrisluke** [comment]
I cannot progress past step: https://staging.vkirirom.com/booking/customer-info

I get prompted for a password:

![image](https://user-images.githubusercontent.com/5694308/76136066-23aeb300-6060-11ea-8b1b-93f4f9420a14.png)

incognito chrome desktop

**Comment by mort3za** [comment]
@paulchrisluke pushed a fix to staging.

**Comment by paulchrisluke** [comment]
Same behavior. Chrome, incognito, windows PC.

![image](https://user-images.githubusercontent.com/5694308/76180696-43291580-61f1-11ea-9290-14a99f4ff21d.png)

When I attempt to continue, thos ID is shown in network:

```
https://www.facebook.com/tr/?id=501612834008296&ev=SubscribedButtonClick&dl=https%3A%2F%2Fstaging.vkirirom.com%2Fbooking%2Fcustomer-info&rl=&if=false&ts=1583724666556&cd[buttonFeatures]=%7B%22classList%22%3A%22v-btn__content%22%2C%22destination%22%3A%22https%3A%2F%2Fstaging.vkirirom.com%2Fbooking%2Fcustomer-info%22%2C%22id%22%3A%22%22%2C%22imageUrl%22%3A%22%22%2C%22innerText%22%3A%22Continue%5Cnkeyboard_arrow_right%22%2C%22numChildButtons%22%3A0%2C%22tag%22%3A%22span%22%7D&cd[buttonText]=Continue%0Akeyboard_arrow_right&cd[formFeatures]=%5B%7B%22id%22%3A%22input-500%22%2C%22name%22%3A%22%22%2C%22tag%22%3A%22input%22%2C%22inputType%22%3A%22text%22%7D%2C%7B%22id%22%3A%22%22%2C%22name%22%3A%22%22%2C%22tag%22%3A%22input%22%2C%22inputType%22%3A%22hidden%22%7D%2C%7B%22id%22%3A%22input-528%22%2C%22name%22%3A%22%22%2C%22tag%22%3A%22input%22%2C%22inputType%22%3A%22text%22%7D%2C%7B%22id%22%3A%22input-531%22%2C%22name%22%3A%22E-mail%22%2C%22tag%22%3A%22input%22%2C%22inputType%22%3A%22email%22%7D%2C%7B%22id%22%3A%22input-534%22%2C%22name%22%3A%22message%22%2C%22tag%22%3A%22textarea%22%2C%22placeholder%22%3A%22Write%20Here...%22%7D%2C%7B%22id%22%3A%22%22%2C%22name%22%3A%22%22%2C%22tag%22%3A%22button%22%7D%5D&cd[pageFeatures]=%7B%22title%22%3A%22vKirirom%20Pine%20Resort%22%7D&cd[parameters]=%5B%5D&sw=375&sh=812&udff[em]=b4d378ab66d51a4877c97be56ef2fe21a9d9311417419bcd5070d88e3a68f3b7&v=2.9.15&r=stable&a=tmgoogletagmanager&ec=15&o=3102&fbp=fb.1.1583724634789.1005458007&it=1583724634659&coo=false&es=automatic&tm=3&rqm=GET
```
I then see a 404 on `https://stagingapi.whynot.earth/api/v0/authentication/register`

**Comment by mort3za** [comment]
@paulchrisluke sorry, it wasn't pushed. this time I tested on staging.vkirirom.com and now is working.

**Comment by paulchrisluke** [comment]
I was able to progress past that step, but unable to book via cash. 404 on:

https://stagingapi.whynot.earth/api/v0/reservations/roomtype/49/reserve

**Comment by paulchrisluke** [comment]
working! Approved.
