### ISSUE TITLE
Corona Campaign

### ISSUE THREAD

**Issue by sotheaYouk** [whynotearth/hotel-website-vkirirom.com#456]
Write 2 blog posts, one for family/couples and another for groups. 

link to the posts: https://docs.google.com/spreadsheets/d/11yCxusIrtTrTploYqE7llVR-PYjQwhYY-XxQaPJus-o/edit?pli=1#gid=550121964

@paulchrisluke

**Comment by paulchrisluke** [comment]
ok we need to make this single landing page. 

make an exciting "weekend experience" page with the same info you need to make an airbnb experience. @Cheanataly , be sure to get that accout up and runnin asap, and start making taht experience. 

@DaroDalya @sotheaYouk write the info you need for that airbnb experience.

after you make the experience, also make a page in the database with the same info. 

we will probably need to go over small details in discord as you build. But try and hurry this along.

**Comment by sotheaYouk** [comment]
@paulchrisluke I'm a little confused. The corona pages and weekend experience page you're talking about are different, right? Corona pages are like special offers on the new piperoom.
