### ISSUE TITLE
add pwa app icon

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#51]
(this can probably be used for our favcon too, just need to resize it smaller)
![62616130_303002710646816_2990129323505090560_n](https://user-images.githubusercontent.com/5694308/59731286-b491f400-926f-11e9-8b0d-33b3939637f7.png)

**Comment by atharva3010** [comment]
I need the icons in the following sizes: 192x192 and 512x512

**Comment by paulchrisluke** [comment]
![vkirirom app icon 192](https://user-images.githubusercontent.com/5694308/59811178-e5872d00-9332-11e9-9d6f-53f9eaf068de.png)
![vkirirom app icon 512](https://user-images.githubusercontent.com/5694308/59811179-e5872d00-9332-11e9-82cc-bb3c3dc05b9e.png)

**Comment by atharva3010** [comment]
They have a white background, can you please make that transparent? @paulchrisluke

**Comment by atharva3010** [comment]
this has been resolved.
