### ISSUE TITLE
revision round

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#88]
1. make entire corporate retreat and menu banners clickable
2. if there is only one image file uploaded, make full screen on listing page?
https://cranky-nightingale-3731fc.netlify.com/listing/Khmer
3. remove number of guests on food
4. change font color of get directions to our grey
5. are our guest/ammenities icons the right grey? They look a little dark.
6. Change CTA button for form to "reserve now" instead of book now, since its just a reservation.
7. https://cranky-nightingale-3731fc.netlify.com/search/blog/ how does this order get determined? Shouldn't partner be right next to buying locally?
![image](https://user-images.githubusercontent.com/5694308/60379489-de140200-9a5d-11e9-8e01-951be1fd07c1.png)
8. when loading a page, content is still being pushed around, ex: https://cranky-nightingale-3731fc.netlify.com/listing/Luxury-Tent you can see the contact button get loaded and then pushed down. Side note, what is the contact button for??
9. top nav items only seem to work for accomodations
10. at the top of search results page, perhaps it would be good to have a filter indicating to the user what they are looking at, instead of "all results" say "all [category]"
11. menu items are not showing the "getting around data" which is where I have added pricing:
https://stagingapi.whynot.earth/api/v0/pages/slug/vkirirom/healthy

**Comment by atharva3010** [comment]
Resolved 1, 2, 3, 9, 10

**Comment by atharva3010** [comment]
resolved all
