### ISSUE TITLE
place-holding content and loading

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#89]
related to that placeholder content we had earlier, preventing content from being pushed around:

when loading a page, content is still being pushed around, ex: https://cranky-nightingale-3731fc.netlify.com/listing/Luxury-Tent you can see the contact button get loaded and then pushed down. Side note, what is the contact button for??

**Comment by atharva3010** [comment]
Contact button was there in the figma

**Comment by paulchrisluke** [comment]
@bamboochow whats the contact button for? 

Can we have placeholder content or containers to allow that content to not be pushed around?

**Comment by atharva3010** [comment]
it's dynamic content, components load dynamically, we toggle components dynamically, the content changes the height on runtime.

**Comment by bamboochow** [comment]
@paulchrisluke contact button was there since before i joined project 
i can take it off?

**Comment by bamboochow** [comment]
@atharva3010 contact sub page button removed

**Comment by paulchrisluke** [comment]
removing contact button good, still working on placeholder content ?

**Comment by atharva3010** [comment]
yeah! some placeholders have been added here and there, for instance, the listing page images used to push down content below as they loaded, that has been fixed. @paulchrisluke every component has a defined size and data loads into it, you won't see much of pushing around apart from text, I am still working on text placeholders.

**Comment by paulchrisluke** [comment]
@atharva3010 I think the solution others are using for text is to simply wrap it in an image box as well? That bottom white area is where the text sits.

![image](https://user-images.githubusercontent.com/5694308/61052357-6ce92d00-a415-11e9-968d-fa7c2b2225b4.png)
