### ISSUE TITLE
footer links and a few other updates

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#96]
- remove book now
- Lease: /listing/nature-city-investment-cambodia-property
- remove collaborate
- partner: /listing/partner 
- remove community outreach
- scholarship: /listing/our-scholarship-program
- Proudly Powered by KIT: https://kit.edu.kh

also can we make those h2 url's the right color? (not blue)
also need /nature-city-investment-cambodia-property to be 301 redirected to /**listing**/nature-city-investment-cambodia-property

**Comment by atharva3010** [comment]
Footer links have been updated.

**Comment by atharva3010** [comment]
redirect done

**Comment by atharva3010** [comment]
links styling fixed
