### ISSUE TITLE
menu search results page, add description

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#97]
“Best lunch spot in Kirirom” (Lonely Planet Guidebook).  vKirirom’s iconic open-air restaurant serves an array of international dishes to complement its core traditional Khmer food.  The restaurant strives to create wonderful healthy food that is locally sourced from local farmers or grown in vKirirom’s own organic garden.  

Book your stay at vKirirom today and enjoy our array of international food!

**Comment by atharva3010** [comment]
done
