### ISSUE TITLE
design total price update on form

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#98]
We need to show total calculations once we select dates. 

![image](https://user-images.githubusercontent.com/5694308/60504493-eda87a80-9ceb-11e9-9cae-0d783b66cad5.png)

Example:

https://www.airbnb.com/rooms/530250?source_impression_id=p3_1562061890_NIdJ8FSbto4R%2Fbeo&s=aIcV54fp&check_in=2019-10-02&guests=1&adults=1&sl_alternate_dates_exclusion=true&check_out=2019-10-05

Since we have different prices per day, we would probably need to show $50+$60+$60 or something like that in per night line

**Comment by bamboochow** [comment]
@atharva3010 design added, will post to discord as well but it's under the master component

**Comment by atharva3010** [comment]
done
